/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GeoKeywordSearchVolumeRecord
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoKeywordSearchVolumeRecordTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeoKeywordSearchVolumeRecord
        //private GeoKeywordSearchVolumeRecord instance;

        public GeoKeywordSearchVolumeRecordTests()
        {
            // TODO uncomment below to create an instance of GeoKeywordSearchVolumeRecord
            //instance = new GeoKeywordSearchVolumeRecord();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoKeywordSearchVolumeRecord
        /// </summary>
        [Fact]
        public void GeoKeywordSearchVolumeRecordInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeoKeywordSearchVolumeRecord
            //Assert.IsType<GeoKeywordSearchVolumeRecord>(instance);
        }

        /// <summary>
        /// Test the property 'Keyword'
        /// </summary>
        [Fact]
        public void KeywordTest()
        {
            // TODO unit test for the property 'Keyword'
        }

        /// <summary>
        /// Test the property 'AiSearchVolume'
        /// </summary>
        [Fact]
        public void AiSearchVolumeTest()
        {
            // TODO unit test for the property 'AiSearchVolume'
        }

        /// <summary>
        /// Test the property 'MonthlySearches'
        /// </summary>
        [Fact]
        public void MonthlySearchesTest()
        {
            // TODO unit test for the property 'MonthlySearches'
        }
    }
}
