/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GeoMentionSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoMentionSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeoMentionSource
        //private GeoMentionSource instance;

        public GeoMentionSourceTests()
        {
            // TODO uncomment below to create an instance of GeoMentionSource
            //instance = new GeoMentionSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoMentionSource
        /// </summary>
        [Fact]
        public void GeoMentionSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeoMentionSource
            //Assert.IsType<GeoMentionSource>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'Snippet'
        /// </summary>
        [Fact]
        public void SnippetTest()
        {
            // TODO unit test for the property 'Snippet'
        }

        /// <summary>
        /// Test the property 'SourceName'
        /// </summary>
        [Fact]
        public void SourceNameTest()
        {
            // TODO unit test for the property 'SourceName'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'PublicationDate'
        /// </summary>
        [Fact]
        public void PublicationDateTest()
        {
            // TODO unit test for the property 'PublicationDate'
        }
    }
}
