/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GeoMentionsTopDomainsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoMentionsTopDomainsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeoMentionsTopDomainsRequest
        //private GeoMentionsTopDomainsRequest instance;

        public GeoMentionsTopDomainsRequestTests()
        {
            // TODO uncomment below to create an instance of GeoMentionsTopDomainsRequest
            //instance = new GeoMentionsTopDomainsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoMentionsTopDomainsRequest
        /// </summary>
        [Fact]
        public void GeoMentionsTopDomainsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeoMentionsTopDomainsRequest
            //Assert.IsType<GeoMentionsTopDomainsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'Engine'
        /// </summary>
        [Fact]
        public void EngineTest()
        {
            // TODO unit test for the property 'Engine'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'LinksScope'
        /// </summary>
        [Fact]
        public void LinksScopeTest()
        {
            // TODO unit test for the property 'LinksScope'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'ItemsListLimit'
        /// </summary>
        [Fact]
        public void ItemsListLimitTest()
        {
            // TODO unit test for the property 'ItemsListLimit'
        }

        /// <summary>
        /// Test the property 'InternalListLimit'
        /// </summary>
        [Fact]
        public void InternalListLimitTest()
        {
            // TODO unit test for the property 'InternalListLimit'
        }
    }
}
