/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GeoMentionsTarget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoMentionsTargetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeoMentionsTarget
        //private GeoMentionsTarget instance;

        public GeoMentionsTargetTests()
        {
            // TODO uncomment below to create an instance of GeoMentionsTarget
            //instance = new GeoMentionsTarget();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoMentionsTarget
        /// </summary>
        [Fact]
        public void GeoMentionsTargetInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeoMentionsTarget
            //Assert.IsType<GeoMentionsTarget>(instance);
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'Keyword'
        /// </summary>
        [Fact]
        public void KeywordTest()
        {
            // TODO unit test for the property 'Keyword'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'Match'
        /// </summary>
        [Fact]
        public void MatchTest()
        {
            // TODO unit test for the property 'Match'
        }

        /// <summary>
        /// Test the property 'IncludeSubdomains'
        /// </summary>
        [Fact]
        public void IncludeSubdomainsTest()
        {
            // TODO unit test for the property 'IncludeSubdomains'
        }
    }
}
