/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GeoSerpResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoSerpResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeoSerpResult
        //private GeoSerpResult instance;

        public GeoSerpResultTests()
        {
            // TODO uncomment below to create an instance of GeoSerpResult
            //instance = new GeoSerpResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoSerpResult
        /// </summary>
        [Fact]
        public void GeoSerpResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeoSerpResult
            //Assert.IsType<GeoSerpResult>(instance);
        }

        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Fact]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }

        /// <summary>
        /// Test the property 'GroupRank'
        /// </summary>
        [Fact]
        public void GroupRankTest()
        {
            // TODO unit test for the property 'GroupRank'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Markdown'
        /// </summary>
        [Fact]
        public void MarkdownTest()
        {
            // TODO unit test for the property 'Markdown'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'References'
        /// </summary>
        [Fact]
        public void ReferencesTest()
        {
            // TODO unit test for the property 'References'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }

        /// <summary>
        /// Test the property 'Sections'
        /// </summary>
        [Fact]
        public void SectionsTest()
        {
            // TODO unit test for the property 'Sections'
        }

        /// <summary>
        /// Test the property 'IsBillable'
        /// </summary>
        [Fact]
        public void IsBillableTest()
        {
            // TODO unit test for the property 'IsBillable'
        }

        /// <summary>
        /// Test the property 'IsTarget'
        /// </summary>
        [Fact]
        public void IsTargetTest()
        {
            // TODO unit test for the property 'IsTarget'
        }

        /// <summary>
        /// Test the property 'Extras'
        /// </summary>
        [Fact]
        public void ExtrasTest()
        {
            // TODO unit test for the property 'Extras'
        }
    }
}
