/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing HackerNewsItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HackerNewsItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HackerNewsItem
        //private HackerNewsItem instance;

        public HackerNewsItemTests()
        {
            // TODO uncomment below to create an instance of HackerNewsItem
            //instance = new HackerNewsItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HackerNewsItem
        /// </summary>
        [Fact]
        public void HackerNewsItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" HackerNewsItem
            //Assert.IsType<HackerNewsItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'By'
        /// </summary>
        [Fact]
        public void ByTest()
        {
            // TODO unit test for the property 'By'
        }

        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Dead'
        /// </summary>
        [Fact]
        public void DeadTest()
        {
            // TODO unit test for the property 'Dead'
        }

        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Fact]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }

        /// <summary>
        /// Test the property 'Poll'
        /// </summary>
        [Fact]
        public void PollTest()
        {
            // TODO unit test for the property 'Poll'
        }

        /// <summary>
        /// Test the property 'Kids'
        /// </summary>
        [Fact]
        public void KidsTest()
        {
            // TODO unit test for the property 'Kids'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Parts'
        /// </summary>
        [Fact]
        public void PartsTest()
        {
            // TODO unit test for the property 'Parts'
        }

        /// <summary>
        /// Test the property 'Descendants'
        /// </summary>
        [Fact]
        public void DescendantsTest()
        {
            // TODO unit test for the property 'Descendants'
        }
    }
}
