/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing InstagramResolveUserIdGet200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstagramResolveUserIdGet200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstagramResolveUserIdGet200ResponseData
        //private InstagramResolveUserIdGet200ResponseData instance;

        public InstagramResolveUserIdGet200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of InstagramResolveUserIdGet200ResponseData
            //instance = new InstagramResolveUserIdGet200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstagramResolveUserIdGet200ResponseData
        /// </summary>
        [Fact]
        public void InstagramResolveUserIdGet200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" InstagramResolveUserIdGet200ResponseData
            //Assert.IsType<InstagramResolveUserIdGet200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}
