/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing InstagramHighlight
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstagramHighlightTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstagramHighlight
        //private InstagramHighlight instance;

        public InstagramHighlightTests()
        {
            // TODO uncomment below to create an instance of InstagramHighlight
            //instance = new InstagramHighlight();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstagramHighlight
        /// </summary>
        [Fact]
        public void InstagramHighlightInstanceTest()
        {
            // TODO uncomment below to test "IsType" InstagramHighlight
            //Assert.IsType<InstagramHighlight>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'CoverUrl'
        /// </summary>
        [Fact]
        public void CoverUrlTest()
        {
            // TODO unit test for the property 'CoverUrl'
        }
    }
}
