/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedinRecommendationRecommender
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedinRecommendationRecommenderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedinRecommendationRecommender
        //private LinkedinRecommendationRecommender instance;

        public LinkedinRecommendationRecommenderTests()
        {
            // TODO uncomment below to create an instance of LinkedinRecommendationRecommender
            //instance = new LinkedinRecommendationRecommender();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedinRecommendationRecommender
        /// </summary>
        [Fact]
        public void LinkedinRecommendationRecommenderInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedinRecommendationRecommender
            //Assert.IsType<LinkedinRecommendationRecommender>(instance);
        }

        /// <summary>
        /// Test the property 'Urn'
        /// </summary>
        [Fact]
        public void UrnTest()
        {
            // TODO unit test for the property 'Urn'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'Headline'
        /// </summary>
        [Fact]
        public void HeadlineTest()
        {
            // TODO unit test for the property 'Headline'
        }

        /// <summary>
        /// Test the property 'AvatarUrl'
        /// </summary>
        [Fact]
        public void AvatarUrlTest()
        {
            // TODO unit test for the property 'AvatarUrl'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'IsPremium'
        /// </summary>
        [Fact]
        public void IsPremiumTest()
        {
            // TODO unit test for the property 'IsPremium'
        }
    }
}
