/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedinSearchIndustriesGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedinSearchIndustriesGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedinSearchIndustriesGet200Response
        //private LinkedinSearchIndustriesGet200Response instance;

        public LinkedinSearchIndustriesGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of LinkedinSearchIndustriesGet200Response
            //instance = new LinkedinSearchIndustriesGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedinSearchIndustriesGet200Response
        /// </summary>
        [Fact]
        public void LinkedinSearchIndustriesGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedinSearchIndustriesGet200Response
            //Assert.IsType<LinkedinSearchIndustriesGet200Response>(instance);
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Billing'
        /// </summary>
        [Fact]
        public void BillingTest()
        {
            // TODO unit test for the property 'Billing'
        }
    }
}
