/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedinUserReaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedinUserReactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedinUserReaction
        //private LinkedinUserReaction instance;

        public LinkedinUserReactionTests()
        {
            // TODO uncomment below to create an instance of LinkedinUserReaction
            //instance = new LinkedinUserReaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedinUserReaction
        /// </summary>
        [Fact]
        public void LinkedinUserReactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedinUserReaction
            //Assert.IsType<LinkedinUserReaction>(instance);
        }

        /// <summary>
        /// Test the property 'ReactionType'
        /// </summary>
        [Fact]
        public void ReactionTypeTest()
        {
            // TODO unit test for the property 'ReactionType'
        }

        /// <summary>
        /// Test the property 'Post'
        /// </summary>
        [Fact]
        public void PostTest()
        {
            // TODO unit test for the property 'Post'
        }
    }
}
