/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedinSearchIndustry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedinSearchIndustryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedinSearchIndustry
        //private LinkedinSearchIndustry instance;

        public LinkedinSearchIndustryTests()
        {
            // TODO uncomment below to create an instance of LinkedinSearchIndustry
            //instance = new LinkedinSearchIndustry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedinSearchIndustry
        /// </summary>
        [Fact]
        public void LinkedinSearchIndustryInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedinSearchIndustry
            //Assert.IsType<LinkedinSearchIndustry>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
