/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedinComment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedinCommentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedinComment
        //private LinkedinComment instance;

        public LinkedinCommentTests()
        {
            // TODO uncomment below to create an instance of LinkedinComment
            //instance = new LinkedinComment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedinComment
        /// </summary>
        [Fact]
        public void LinkedinCommentInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedinComment
            //Assert.IsType<LinkedinComment>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Urn'
        /// </summary>
        [Fact]
        public void UrnTest()
        {
            // TODO unit test for the property 'Urn'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'LikeCount'
        /// </summary>
        [Fact]
        public void LikeCountTest()
        {
            // TODO unit test for the property 'LikeCount'
        }

        /// <summary>
        /// Test the property 'ReplyCount'
        /// </summary>
        [Fact]
        public void ReplyCountTest()
        {
            // TODO unit test for the property 'ReplyCount'
        }

        /// <summary>
        /// Test the property 'IsPinned'
        /// </summary>
        [Fact]
        public void IsPinnedTest()
        {
            // TODO unit test for the property 'IsPinned'
        }

        /// <summary>
        /// Test the property 'IsEdited'
        /// </summary>
        [Fact]
        public void IsEditedTest()
        {
            // TODO unit test for the property 'IsEdited'
        }

        /// <summary>
        /// Test the property 'IsAuthor'
        /// </summary>
        [Fact]
        public void IsAuthorTest()
        {
            // TODO unit test for the property 'IsAuthor'
        }

        /// <summary>
        /// Test the property 'HasPreviousReplies'
        /// </summary>
        [Fact]
        public void HasPreviousRepliesTest()
        {
            // TODO unit test for the property 'HasPreviousReplies'
        }

        /// <summary>
        /// Test the property 'PreviousRepliesToken'
        /// </summary>
        [Fact]
        public void PreviousRepliesTokenTest()
        {
            // TODO unit test for the property 'PreviousRepliesToken'
        }

        /// <summary>
        /// Test the property 'Reactions'
        /// </summary>
        [Fact]
        public void ReactionsTest()
        {
            // TODO unit test for the property 'Reactions'
        }

        /// <summary>
        /// Test the property 'Commenter'
        /// </summary>
        [Fact]
        public void CommenterTest()
        {
            // TODO unit test for the property 'Commenter'
        }
    }
}
