/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LinkedinVolunteer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkedinVolunteerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkedinVolunteer
        //private LinkedinVolunteer instance;

        public LinkedinVolunteerTests()
        {
            // TODO uncomment below to create an instance of LinkedinVolunteer
            //instance = new LinkedinVolunteer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedinVolunteer
        /// </summary>
        [Fact]
        public void LinkedinVolunteerInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkedinVolunteer
            //Assert.IsType<LinkedinVolunteer>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Cause'
        /// </summary>
        [Fact]
        public void CauseTest()
        {
            // TODO unit test for the property 'Cause'
        }

        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Fact]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
