/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing NewsSearchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewsSearchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewsSearchRequest
        //private NewsSearchRequest instance;

        public NewsSearchRequestTests()
        {
            // TODO uncomment below to create an instance of NewsSearchRequest
            //instance = new NewsSearchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewsSearchRequest
        /// </summary>
        [Fact]
        public void NewsSearchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewsSearchRequest
            //Assert.IsType<NewsSearchRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Fact]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }

        /// <summary>
        /// Test the property 'Os'
        /// </summary>
        [Fact]
        public void OsTest()
        {
            // TODO unit test for the property 'Os'
        }
    }
}
