/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing RedditSubreddit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RedditSubredditTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RedditSubreddit
        //private RedditSubreddit instance;

        public RedditSubredditTests()
        {
            // TODO uncomment below to create an instance of RedditSubreddit
            //instance = new RedditSubreddit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RedditSubreddit
        /// </summary>
        [Fact]
        public void RedditSubredditInstanceTest()
        {
            // TODO uncomment below to test "IsType" RedditSubreddit
            //Assert.IsType<RedditSubreddit>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'SubredditT5Id'
        /// </summary>
        [Fact]
        public void SubredditT5IdTest()
        {
            // TODO unit test for the property 'SubredditT5Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PrefixedName'
        /// </summary>
        [Fact]
        public void PrefixedNameTest()
        {
            // TODO unit test for the property 'PrefixedName'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'SubscribersCount'
        /// </summary>
        [Fact]
        public void SubscribersCountTest()
        {
            // TODO unit test for the property 'SubscribersCount'
        }

        /// <summary>
        /// Test the property 'ActiveCount'
        /// </summary>
        [Fact]
        public void ActiveCountTest()
        {
            // TODO unit test for the property 'ActiveCount'
        }

        /// <summary>
        /// Test the property 'IsNsfw'
        /// </summary>
        [Fact]
        public void IsNsfwTest()
        {
            // TODO unit test for the property 'IsNsfw'
        }
    }
}
