/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoAutocompleteLocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoAutocompleteLocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoAutocompleteLocation
        //private SeoAutocompleteLocation instance;

        public SeoAutocompleteLocationTests()
        {
            // TODO uncomment below to create an instance of SeoAutocompleteLocation
            //instance = new SeoAutocompleteLocation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoAutocompleteLocation
        /// </summary>
        [Fact]
        public void SeoAutocompleteLocationInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoAutocompleteLocation
            //Assert.IsType<SeoAutocompleteLocation>(instance);
        }
    }
}
