/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoBacklinksPageIntersectionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoBacklinksPageIntersectionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoBacklinksPageIntersectionResponse
        //private SeoBacklinksPageIntersectionResponse instance;

        public SeoBacklinksPageIntersectionResponseTests()
        {
            // TODO uncomment below to create an instance of SeoBacklinksPageIntersectionResponse
            //instance = new SeoBacklinksPageIntersectionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoBacklinksPageIntersectionResponse
        /// </summary>
        [Fact]
        public void SeoBacklinksPageIntersectionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoBacklinksPageIntersectionResponse
            //Assert.IsType<SeoBacklinksPageIntersectionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Targets'
        /// </summary>
        [Fact]
        public void TargetsTest()
        {
            // TODO unit test for the property 'Targets'
        }

        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Fact]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
