/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoBacklinksSummaryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoBacklinksSummaryRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoBacklinksSummaryRequest
        //private SeoBacklinksSummaryRequest instance;

        public SeoBacklinksSummaryRequestTests()
        {
            // TODO uncomment below to create an instance of SeoBacklinksSummaryRequest
            //instance = new SeoBacklinksSummaryRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoBacklinksSummaryRequest
        /// </summary>
        [Fact]
        public void SeoBacklinksSummaryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoBacklinksSummaryRequest
            //Assert.IsType<SeoBacklinksSummaryRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'BacklinksStatusType'
        /// </summary>
        [Fact]
        public void BacklinksStatusTypeTest()
        {
            // TODO unit test for the property 'BacklinksStatusType'
        }

        /// <summary>
        /// Test the property 'IncludeSubdomains'
        /// </summary>
        [Fact]
        public void IncludeSubdomainsTest()
        {
            // TODO unit test for the property 'IncludeSubdomains'
        }

        /// <summary>
        /// Test the property 'IncludeIndirectLinks'
        /// </summary>
        [Fact]
        public void IncludeIndirectLinksTest()
        {
            // TODO unit test for the property 'IncludeIndirectLinks'
        }

        /// <summary>
        /// Test the property 'ExcludeInternalBacklinks'
        /// </summary>
        [Fact]
        public void ExcludeInternalBacklinksTest()
        {
            // TODO unit test for the property 'ExcludeInternalBacklinks'
        }

        /// <summary>
        /// Test the property 'InternalListLimit'
        /// </summary>
        [Fact]
        public void InternalListLimitTest()
        {
            // TODO unit test for the property 'InternalListLimit'
        }

        /// <summary>
        /// Test the property 'RankScale'
        /// </summary>
        [Fact]
        public void RankScaleTest()
        {
            // TODO unit test for the property 'RankScale'
        }

        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Fact]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }
    }
}
