/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoBacklinksBulkReferringDomainsItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoBacklinksBulkReferringDomainsItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoBacklinksBulkReferringDomainsItem
        //private SeoBacklinksBulkReferringDomainsItem instance;

        public SeoBacklinksBulkReferringDomainsItemTests()
        {
            // TODO uncomment below to create an instance of SeoBacklinksBulkReferringDomainsItem
            //instance = new SeoBacklinksBulkReferringDomainsItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoBacklinksBulkReferringDomainsItem
        /// </summary>
        [Fact]
        public void SeoBacklinksBulkReferringDomainsItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoBacklinksBulkReferringDomainsItem
            //Assert.IsType<SeoBacklinksBulkReferringDomainsItem>(instance);
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'ReferringDomains'
        /// </summary>
        [Fact]
        public void ReferringDomainsTest()
        {
            // TODO unit test for the property 'ReferringDomains'
        }

        /// <summary>
        /// Test the property 'ReferringDomainsNofollow'
        /// </summary>
        [Fact]
        public void ReferringDomainsNofollowTest()
        {
            // TODO unit test for the property 'ReferringDomainsNofollow'
        }

        /// <summary>
        /// Test the property 'ReferringMainDomains'
        /// </summary>
        [Fact]
        public void ReferringMainDomainsTest()
        {
            // TODO unit test for the property 'ReferringMainDomains'
        }

        /// <summary>
        /// Test the property 'ReferringMainDomainsNofollow'
        /// </summary>
        [Fact]
        public void ReferringMainDomainsNofollowTest()
        {
            // TODO unit test for the property 'ReferringMainDomainsNofollow'
        }
    }
}
