/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoBacklinksDomainIntersectionItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoBacklinksDomainIntersectionItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoBacklinksDomainIntersectionItem
        //private SeoBacklinksDomainIntersectionItem instance;

        public SeoBacklinksDomainIntersectionItemTests()
        {
            // TODO uncomment below to create an instance of SeoBacklinksDomainIntersectionItem
            //instance = new SeoBacklinksDomainIntersectionItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoBacklinksDomainIntersectionItem
        /// </summary>
        [Fact]
        public void SeoBacklinksDomainIntersectionItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoBacklinksDomainIntersectionItem
            //Assert.IsType<SeoBacklinksDomainIntersectionItem>(instance);
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'IntersectionsCount'
        /// </summary>
        [Fact]
        public void IntersectionsCountTest()
        {
            // TODO unit test for the property 'IntersectionsCount'
        }

        /// <summary>
        /// Test the property 'ReferringTo'
        /// </summary>
        [Fact]
        public void ReferringToTest()
        {
            // TODO unit test for the property 'ReferringTo'
        }
    }
}
