/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoBacklinksTimeseriesNewLostResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoBacklinksTimeseriesNewLostResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoBacklinksTimeseriesNewLostResponse
        //private SeoBacklinksTimeseriesNewLostResponse instance;

        public SeoBacklinksTimeseriesNewLostResponseTests()
        {
            // TODO uncomment below to create an instance of SeoBacklinksTimeseriesNewLostResponse
            //instance = new SeoBacklinksTimeseriesNewLostResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoBacklinksTimeseriesNewLostResponse
        /// </summary>
        [Fact]
        public void SeoBacklinksTimeseriesNewLostResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoBacklinksTimeseriesNewLostResponse
            //Assert.IsType<SeoBacklinksTimeseriesNewLostResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'GroupRange'
        /// </summary>
        [Fact]
        public void GroupRangeTest()
        {
            // TODO unit test for the property 'GroupRange'
        }

        /// <summary>
        /// Test the property 'DateFrom'
        /// </summary>
        [Fact]
        public void DateFromTest()
        {
            // TODO unit test for the property 'DateFrom'
        }

        /// <summary>
        /// Test the property 'DateTo'
        /// </summary>
        [Fact]
        public void DateToTest()
        {
            // TODO unit test for the property 'DateTo'
        }

        /// <summary>
        /// Test the property 'Series'
        /// </summary>
        [Fact]
        public void SeriesTest()
        {
            // TODO unit test for the property 'Series'
        }
    }
}
