/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoHistoricalRankItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoHistoricalRankItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoHistoricalRankItem
        //private SeoHistoricalRankItem instance;

        public SeoHistoricalRankItemTests()
        {
            // TODO uncomment below to create an instance of SeoHistoricalRankItem
            //instance = new SeoHistoricalRankItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoHistoricalRankItem
        /// </summary>
        [Fact]
        public void SeoHistoricalRankItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoHistoricalRankItem
            //Assert.IsType<SeoHistoricalRankItem>(instance);
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }

        /// <summary>
        /// Test the property 'Organic'
        /// </summary>
        [Fact]
        public void OrganicTest()
        {
            // TODO unit test for the property 'Organic'
        }

        /// <summary>
        /// Test the property 'Paid'
        /// </summary>
        [Fact]
        public void PaidTest()
        {
            // TODO unit test for the property 'Paid'
        }
    }
}
