/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoKeywordSearchVolumeTrend
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoKeywordSearchVolumeTrendTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoKeywordSearchVolumeTrend
        //private SeoKeywordSearchVolumeTrend instance;

        public SeoKeywordSearchVolumeTrendTests()
        {
            // TODO uncomment below to create an instance of SeoKeywordSearchVolumeTrend
            //instance = new SeoKeywordSearchVolumeTrend();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoKeywordSearchVolumeTrend
        /// </summary>
        [Fact]
        public void SeoKeywordSearchVolumeTrendInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoKeywordSearchVolumeTrend
            //Assert.IsType<SeoKeywordSearchVolumeTrend>(instance);
        }

        /// <summary>
        /// Test the property 'Monthly'
        /// </summary>
        [Fact]
        public void MonthlyTest()
        {
            // TODO unit test for the property 'Monthly'
        }

        /// <summary>
        /// Test the property 'Quarterly'
        /// </summary>
        [Fact]
        public void QuarterlyTest()
        {
            // TODO unit test for the property 'Quarterly'
        }

        /// <summary>
        /// Test the property 'Yearly'
        /// </summary>
        [Fact]
        public void YearlyTest()
        {
            // TODO unit test for the property 'Yearly'
        }
    }
}
