/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoKeywordSuggestionsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoKeywordSuggestionsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoKeywordSuggestionsResponse
        //private SeoKeywordSuggestionsResponse instance;

        public SeoKeywordSuggestionsResponseTests()
        {
            // TODO uncomment below to create an instance of SeoKeywordSuggestionsResponse
            //instance = new SeoKeywordSuggestionsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoKeywordSuggestionsResponse
        /// </summary>
        [Fact]
        public void SeoKeywordSuggestionsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoKeywordSuggestionsResponse
            //Assert.IsType<SeoKeywordSuggestionsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SeedKeyword'
        /// </summary>
        [Fact]
        public void SeedKeywordTest()
        {
            // TODO unit test for the property 'SeedKeyword'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Fact]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

        /// <summary>
        /// Test the property 'OffsetToken'
        /// </summary>
        [Fact]
        public void OffsetTokenTest()
        {
            // TODO unit test for the property 'OffsetToken'
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
