/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SeoSubdomainItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeoSubdomainItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeoSubdomainItem
        //private SeoSubdomainItem instance;

        public SeoSubdomainItemTests()
        {
            // TODO uncomment below to create an instance of SeoSubdomainItem
            //instance = new SeoSubdomainItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoSubdomainItem
        /// </summary>
        [Fact]
        public void SeoSubdomainItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeoSubdomainItem
            //Assert.IsType<SeoSubdomainItem>(instance);
        }

        /// <summary>
        /// Test the property 'Subdomain'
        /// </summary>
        [Fact]
        public void SubdomainTest()
        {
            // TODO unit test for the property 'Subdomain'
        }

        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Fact]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }
    }
}
