/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unifapi.Sdk.Model;
using Unifapi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Unifapi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing XCommunity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XCommunityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XCommunity
        //private XCommunity instance;

        public XCommunityTests()
        {
            // TODO uncomment below to create an instance of XCommunity
            //instance = new XCommunity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XCommunity
        /// </summary>
        [Fact]
        public void XCommunityInstanceTest()
        {
            // TODO uncomment below to test "IsType" XCommunity
            //Assert.IsType<XCommunity>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'MemberCount'
        /// </summary>
        [Fact]
        public void MemberCountTest()
        {
            // TODO unit test for the property 'MemberCount'
        }

        /// <summary>
        /// Test the property 'Access'
        /// </summary>
        [Fact]
        public void AccessTest()
        {
            // TODO unit test for the property 'Access'
        }

        /// <summary>
        /// Test the property 'JoinPolicy'
        /// </summary>
        [Fact]
        public void JoinPolicyTest()
        {
            // TODO unit test for the property 'JoinPolicy'
        }
    }
}
