/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Unifapi.Sdk.Client;
using Unifapi.Sdk.Api;
// uncomment below to import models
//using Unifapi.Sdk.Model;

namespace Unifapi.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing BrowserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BrowserApiTests : IDisposable
    {
        private BrowserApi instance;

        public BrowserApiTests()
        {
            instance = new BrowserApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrowserApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BrowserApi
            //Assert.IsType<BrowserApi>(instance);
        }

        /// <summary>
        /// Test BrowserHtmlPost
        /// </summary>
        [Fact]
        public void BrowserHtmlPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BrowserHtmlRequest? browserHtmlRequest = null;
            //var response = instance.BrowserHtmlPost(browserHtmlRequest);
            //Assert.IsType<BrowserHtmlPost200Response>(response);
        }

        /// <summary>
        /// Test BrowserLinksPost
        /// </summary>
        [Fact]
        public void BrowserLinksPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BrowserLinksRequest? browserLinksRequest = null;
            //var response = instance.BrowserLinksPost(browserLinksRequest);
            //Assert.IsType<BrowserLinksPost200Response>(response);
        }

        /// <summary>
        /// Test BrowserMarkdownPost
        /// </summary>
        [Fact]
        public void BrowserMarkdownPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BrowserMarkdownRequest? browserMarkdownRequest = null;
            //var response = instance.BrowserMarkdownPost(browserMarkdownRequest);
            //Assert.IsType<BrowserMarkdownPost200Response>(response);
        }

        /// <summary>
        /// Test BrowserScreenshotPost
        /// </summary>
        [Fact]
        public void BrowserScreenshotPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BrowserScreenshotRequest? browserScreenshotRequest = null;
            //var response = instance.BrowserScreenshotPost(browserScreenshotRequest);
            //Assert.IsType<BrowserScreenshotPost200Response>(response);
        }
    }
}
