/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Unifapi.Sdk.Client;
using Unifapi.Sdk.Api;
// uncomment below to import models
//using Unifapi.Sdk.Model;

namespace Unifapi.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing InstagramApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InstagramApiTests : IDisposable
    {
        private InstagramApi instance;

        public InstagramApiTests()
        {
            instance = new InstagramApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstagramApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InstagramApi
            //Assert.IsType<InstagramApi>(instance);
        }

        /// <summary>
        /// Test InstagramExploreGet
        /// </summary>
        [Fact]
        public void InstagramExploreGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? cursor = null;
            //var response = instance.InstagramExploreGet(cursor);
            //Assert.IsType<InstagramExploreGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramLocationsIdGet
        /// </summary>
        [Fact]
        public void InstagramLocationsIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.InstagramLocationsIdGet(id);
            //Assert.IsType<InstagramLocationsIdGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramLocationsIdNearbyGet
        /// </summary>
        [Fact]
        public void InstagramLocationsIdNearbyGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.InstagramLocationsIdNearbyGet(id);
            //Assert.IsType<InstagramLocationsIdNearbyGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramLocationsIdPostsGet
        /// </summary>
        [Fact]
        public void InstagramLocationsIdPostsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string? cursor = null;
            //string? tab = null;
            //var response = instance.InstagramLocationsIdPostsGet(id, cursor, tab);
            //Assert.IsType<InstagramExploreGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramPostsShortcodeCommentsCommentIdRepliesGet
        /// </summary>
        [Fact]
        public void InstagramPostsShortcodeCommentsCommentIdRepliesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string shortcode = null;
            //string commentId = null;
            //string? cursor = null;
            //var response = instance.InstagramPostsShortcodeCommentsCommentIdRepliesGet(shortcode, commentId, cursor);
            //Assert.IsType<InstagramPostsShortcodeCommentsCommentIdRepliesGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramPostsShortcodeCommentsGet
        /// </summary>
        [Fact]
        public void InstagramPostsShortcodeCommentsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string shortcode = null;
            //string? cursor = null;
            //string? sort = null;
            //var response = instance.InstagramPostsShortcodeCommentsGet(shortcode, cursor, sort);
            //Assert.IsType<InstagramPostsShortcodeCommentsCommentIdRepliesGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramPostsShortcodeGet
        /// </summary>
        [Fact]
        public void InstagramPostsShortcodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string shortcode = null;
            //var response = instance.InstagramPostsShortcodeGet(shortcode);
            //Assert.IsType<InstagramPostsShortcodeGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramReelsRecommendedGet
        /// </summary>
        [Fact]
        public void InstagramReelsRecommendedGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? cursor = null;
            //var response = instance.InstagramReelsRecommendedGet(cursor);
            //Assert.IsType<InstagramExploreGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramResolveMediaIdGet
        /// </summary>
        [Fact]
        public void InstagramResolveMediaIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string shortcode = null;
            //var response = instance.InstagramResolveMediaIdGet(shortcode);
            //Assert.IsType<InstagramResolveMediaIdGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramResolveShortcodeFromMediaGet
        /// </summary>
        [Fact]
        public void InstagramResolveShortcodeFromMediaGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string mediaId = null;
            //var response = instance.InstagramResolveShortcodeFromMediaGet(mediaId);
            //Assert.IsType<InstagramResolveMediaIdGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramResolveShortcodeGet
        /// </summary>
        [Fact]
        public void InstagramResolveShortcodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string url = null;
            //var response = instance.InstagramResolveShortcodeGet(url);
            //Assert.IsType<InstagramResolveShortcodeGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramResolveUserIdGet
        /// </summary>
        [Fact]
        public void InstagramResolveUserIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.InstagramResolveUserIdGet(username);
            //Assert.IsType<InstagramResolveUserIdGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramSearchGet
        /// </summary>
        [Fact]
        public void InstagramSearchGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string q = null;
            //string? cursor = null;
            //var response = instance.InstagramSearchGet(q, cursor);
            //Assert.IsType<InstagramExploreGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernameFollowersGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernameFollowersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string? cursor = null;
            //var response = instance.InstagramUsersUsernameFollowersGet(username, cursor);
            //Assert.IsType<InstagramUsersUsernameFollowersGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernameFollowingGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernameFollowingGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string? cursor = null;
            //var response = instance.InstagramUsersUsernameFollowingGet(username, cursor);
            //Assert.IsType<InstagramUsersUsernameFollowersGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernameFormerUsernamesGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernameFormerUsernamesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.InstagramUsersUsernameFormerUsernamesGet(username);
            //Assert.IsType<InstagramUsersUsernameFormerUsernamesGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernameGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.InstagramUsersUsernameGet(username);
            //Assert.IsType<InstagramUsersUsernameGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernameHighlightsGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernameHighlightsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string? cursor = null;
            //var response = instance.InstagramUsersUsernameHighlightsGet(username, cursor);
            //Assert.IsType<InstagramUsersUsernameHighlightsGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernamePostsGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernamePostsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string? cursor = null;
            //var response = instance.InstagramUsersUsernamePostsGet(username, cursor);
            //Assert.IsType<InstagramExploreGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernameReelsGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernameReelsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string? cursor = null;
            //var response = instance.InstagramUsersUsernameReelsGet(username, cursor);
            //Assert.IsType<InstagramExploreGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernameStoriesGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernameStoriesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.InstagramUsersUsernameStoriesGet(username);
            //Assert.IsType<InstagramExploreGet200Response>(response);
        }

        /// <summary>
        /// Test InstagramUsersUsernameTaggedPostsGet
        /// </summary>
        [Fact]
        public void InstagramUsersUsernameTaggedPostsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string? cursor = null;
            //var response = instance.InstagramUsersUsernameTaggedPostsGet(username, cursor);
            //Assert.IsType<InstagramExploreGet200Response>(response);
        }
    }
}
