/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Unifapi.Sdk.Client;
using Unifapi.Sdk.Api;
// uncomment below to import models
//using Unifapi.Sdk.Model;

namespace Unifapi.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing SeoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SeoApiTests : IDisposable
    {
        private SeoApi instance;

        public SeoApiTests()
        {
            instance = new SeoApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeoApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SeoApi
            //Assert.IsType<SeoApi>(instance);
        }

        /// <summary>
        /// Test SeoBacklinksAnchorsPost
        /// </summary>
        [Fact]
        public void SeoBacklinksAnchorsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksAnchorsRequest? seoBacklinksAnchorsRequest = null;
            //var response = instance.SeoBacklinksAnchorsPost(seoBacklinksAnchorsRequest);
            //Assert.IsType<SeoBacklinksAnchorsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksBulkBacklinksPost
        /// </summary>
        [Fact]
        public void SeoBacklinksBulkBacklinksPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksBulkBacklinksRequest? seoBacklinksBulkBacklinksRequest = null;
            //var response = instance.SeoBacklinksBulkBacklinksPost(seoBacklinksBulkBacklinksRequest);
            //Assert.IsType<SeoBacklinksBulkBacklinksPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksBulkNewLostBacklinksPost
        /// </summary>
        [Fact]
        public void SeoBacklinksBulkNewLostBacklinksPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksBulkNewLostBacklinksRequest? seoBacklinksBulkNewLostBacklinksRequest = null;
            //var response = instance.SeoBacklinksBulkNewLostBacklinksPost(seoBacklinksBulkNewLostBacklinksRequest);
            //Assert.IsType<SeoBacklinksBulkNewLostBacklinksPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksBulkNewLostReferringDomainsPost
        /// </summary>
        [Fact]
        public void SeoBacklinksBulkNewLostReferringDomainsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksBulkNewLostReferringDomainsRequest? seoBacklinksBulkNewLostReferringDomainsRequest = null;
            //var response = instance.SeoBacklinksBulkNewLostReferringDomainsPost(seoBacklinksBulkNewLostReferringDomainsRequest);
            //Assert.IsType<SeoBacklinksBulkNewLostReferringDomainsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksBulkPagesSummaryPost
        /// </summary>
        [Fact]
        public void SeoBacklinksBulkPagesSummaryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksBulkPagesSummaryRequest? seoBacklinksBulkPagesSummaryRequest = null;
            //var response = instance.SeoBacklinksBulkPagesSummaryPost(seoBacklinksBulkPagesSummaryRequest);
            //Assert.IsType<SeoBacklinksBulkPagesSummaryPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksBulkRanksPost
        /// </summary>
        [Fact]
        public void SeoBacklinksBulkRanksPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksBulkRanksRequest? seoBacklinksBulkRanksRequest = null;
            //var response = instance.SeoBacklinksBulkRanksPost(seoBacklinksBulkRanksRequest);
            //Assert.IsType<SeoBacklinksBulkRanksPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksBulkReferringDomainsPost
        /// </summary>
        [Fact]
        public void SeoBacklinksBulkReferringDomainsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksBulkReferringDomainsRequest? seoBacklinksBulkReferringDomainsRequest = null;
            //var response = instance.SeoBacklinksBulkReferringDomainsPost(seoBacklinksBulkReferringDomainsRequest);
            //Assert.IsType<SeoBacklinksBulkReferringDomainsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksBulkSpamScorePost
        /// </summary>
        [Fact]
        public void SeoBacklinksBulkSpamScorePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksBulkSpamScoreRequest? seoBacklinksBulkSpamScoreRequest = null;
            //var response = instance.SeoBacklinksBulkSpamScorePost(seoBacklinksBulkSpamScoreRequest);
            //Assert.IsType<SeoBacklinksBulkSpamScorePost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksCompetitorsPost
        /// </summary>
        [Fact]
        public void SeoBacklinksCompetitorsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksCompetitorsRequest? seoBacklinksCompetitorsRequest = null;
            //var response = instance.SeoBacklinksCompetitorsPost(seoBacklinksCompetitorsRequest);
            //Assert.IsType<SeoBacklinksCompetitorsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksDomainIntersectionPost
        /// </summary>
        [Fact]
        public void SeoBacklinksDomainIntersectionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksDomainIntersectionRequest? seoBacklinksDomainIntersectionRequest = null;
            //var response = instance.SeoBacklinksDomainIntersectionPost(seoBacklinksDomainIntersectionRequest);
            //Assert.IsType<SeoBacklinksDomainIntersectionPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksDomainPagesPost
        /// </summary>
        [Fact]
        public void SeoBacklinksDomainPagesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksDomainPagesRequest? seoBacklinksDomainPagesRequest = null;
            //var response = instance.SeoBacklinksDomainPagesPost(seoBacklinksDomainPagesRequest);
            //Assert.IsType<SeoBacklinksDomainPagesPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksDomainPagesSummaryPost
        /// </summary>
        [Fact]
        public void SeoBacklinksDomainPagesSummaryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksDomainPagesSummaryRequest? seoBacklinksDomainPagesSummaryRequest = null;
            //var response = instance.SeoBacklinksDomainPagesSummaryPost(seoBacklinksDomainPagesSummaryRequest);
            //Assert.IsType<SeoBacklinksDomainPagesSummaryPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksHistoryPost
        /// </summary>
        [Fact]
        public void SeoBacklinksHistoryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksHistoryRequest? seoBacklinksHistoryRequest = null;
            //var response = instance.SeoBacklinksHistoryPost(seoBacklinksHistoryRequest);
            //Assert.IsType<SeoBacklinksHistoryPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksListPost
        /// </summary>
        [Fact]
        public void SeoBacklinksListPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksListRequest? seoBacklinksListRequest = null;
            //var response = instance.SeoBacklinksListPost(seoBacklinksListRequest);
            //Assert.IsType<SeoBacklinksListPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksPageIntersectionPost
        /// </summary>
        [Fact]
        public void SeoBacklinksPageIntersectionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksPageIntersectionRequest? seoBacklinksPageIntersectionRequest = null;
            //var response = instance.SeoBacklinksPageIntersectionPost(seoBacklinksPageIntersectionRequest);
            //Assert.IsType<SeoBacklinksPageIntersectionPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksReferringDomainsPost
        /// </summary>
        [Fact]
        public void SeoBacklinksReferringDomainsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoReferringDomainsRequest? seoReferringDomainsRequest = null;
            //var response = instance.SeoBacklinksReferringDomainsPost(seoReferringDomainsRequest);
            //Assert.IsType<SeoBacklinksReferringDomainsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksReferringNetworksPost
        /// </summary>
        [Fact]
        public void SeoBacklinksReferringNetworksPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksReferringNetworksRequest? seoBacklinksReferringNetworksRequest = null;
            //var response = instance.SeoBacklinksReferringNetworksPost(seoBacklinksReferringNetworksRequest);
            //Assert.IsType<SeoBacklinksReferringNetworksPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksSummaryPost
        /// </summary>
        [Fact]
        public void SeoBacklinksSummaryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksSummaryRequest? seoBacklinksSummaryRequest = null;
            //var response = instance.SeoBacklinksSummaryPost(seoBacklinksSummaryRequest);
            //Assert.IsType<SeoBacklinksSummaryPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksTimeseriesNewLostPost
        /// </summary>
        [Fact]
        public void SeoBacklinksTimeseriesNewLostPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksTimeseriesNewLostRequest? seoBacklinksTimeseriesNewLostRequest = null;
            //var response = instance.SeoBacklinksTimeseriesNewLostPost(seoBacklinksTimeseriesNewLostRequest);
            //Assert.IsType<SeoBacklinksTimeseriesNewLostPost200Response>(response);
        }

        /// <summary>
        /// Test SeoBacklinksTimeseriesPost
        /// </summary>
        [Fact]
        public void SeoBacklinksTimeseriesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBacklinksTimeseriesRequest? seoBacklinksTimeseriesRequest = null;
            //var response = instance.SeoBacklinksTimeseriesPost(seoBacklinksTimeseriesRequest);
            //Assert.IsType<SeoBacklinksTimeseriesPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsBulkTrafficPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsBulkTrafficPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoBulkTrafficRequest? seoBulkTrafficRequest = null;
            //var response = instance.SeoCompetitorsBulkTrafficPost(seoBulkTrafficRequest);
            //Assert.IsType<SeoCompetitorsBulkTrafficPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsDomainIntersectionPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsDomainIntersectionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoDomainIntersectionRequest? seoDomainIntersectionRequest = null;
            //var response = instance.SeoCompetitorsDomainIntersectionPost(seoDomainIntersectionRequest);
            //Assert.IsType<SeoCompetitorsDomainIntersectionPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsDomainPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsDomainPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoCompetitorsDomainRequest? seoCompetitorsDomainRequest = null;
            //var response = instance.SeoCompetitorsDomainPost(seoCompetitorsDomainRequest);
            //Assert.IsType<SeoCompetitorsDomainPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsDomainRankOverviewPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsDomainRankOverviewPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoDomainRankOverviewRequest? seoDomainRankOverviewRequest = null;
            //var response = instance.SeoCompetitorsDomainRankOverviewPost(seoDomainRankOverviewRequest);
            //Assert.IsType<SeoCompetitorsDomainRankOverviewPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsHistoricalBulkTrafficPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsHistoricalBulkTrafficPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoHistoricalBulkTrafficRequest? seoHistoricalBulkTrafficRequest = null;
            //var response = instance.SeoCompetitorsHistoricalBulkTrafficPost(seoHistoricalBulkTrafficRequest);
            //Assert.IsType<SeoCompetitorsHistoricalBulkTrafficPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsHistoricalRankOverviewPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsHistoricalRankOverviewPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoHistoricalRankOverviewRequest? seoHistoricalRankOverviewRequest = null;
            //var response = instance.SeoCompetitorsHistoricalRankOverviewPost(seoHistoricalRankOverviewRequest);
            //Assert.IsType<SeoCompetitorsHistoricalRankOverviewPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsHistoricalSerpsPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsHistoricalSerpsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoHistoricalSerpsRequest? seoHistoricalSerpsRequest = null;
            //var response = instance.SeoCompetitorsHistoricalSerpsPost(seoHistoricalSerpsRequest);
            //Assert.IsType<SeoCompetitorsHistoricalSerpsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsPageIntersectionPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsPageIntersectionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoPageIntersectionRequest? seoPageIntersectionRequest = null;
            //var response = instance.SeoCompetitorsPageIntersectionPost(seoPageIntersectionRequest);
            //Assert.IsType<SeoCompetitorsPageIntersectionPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsRankedKeywordsPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsRankedKeywordsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoRankedKeywordsRequest? seoRankedKeywordsRequest = null;
            //var response = instance.SeoCompetitorsRankedKeywordsPost(seoRankedKeywordsRequest);
            //Assert.IsType<SeoCompetitorsRankedKeywordsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsRelevantPagesPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsRelevantPagesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoRelevantPagesRequest? seoRelevantPagesRequest = null;
            //var response = instance.SeoCompetitorsRelevantPagesPost(seoRelevantPagesRequest);
            //Assert.IsType<SeoCompetitorsRelevantPagesPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsSerpPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsSerpPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoSerpCompetitorsRequest? seoSerpCompetitorsRequest = null;
            //var response = instance.SeoCompetitorsSerpPost(seoSerpCompetitorsRequest);
            //Assert.IsType<SeoCompetitorsSerpPost200Response>(response);
        }

        /// <summary>
        /// Test SeoCompetitorsSubdomainsPost
        /// </summary>
        [Fact]
        public void SeoCompetitorsSubdomainsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoSubdomainsRequest? seoSubdomainsRequest = null;
            //var response = instance.SeoCompetitorsSubdomainsPost(seoSubdomainsRequest);
            //Assert.IsType<SeoCompetitorsSubdomainsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsAutocompletePost
        /// </summary>
        [Fact]
        public void SeoKeywordsAutocompletePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoKeywordAutocompleteRequest? seoKeywordAutocompleteRequest = null;
            //var response = instance.SeoKeywordsAutocompletePost(seoKeywordAutocompleteRequest);
            //Assert.IsType<SeoKeywordsAutocompletePost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsDifficultyPost
        /// </summary>
        [Fact]
        public void SeoKeywordsDifficultyPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoKeywordDifficultyRequest? seoKeywordDifficultyRequest = null;
            //var response = instance.SeoKeywordsDifficultyPost(seoKeywordDifficultyRequest);
            //Assert.IsType<SeoKeywordsDifficultyPost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsForSitePost
        /// </summary>
        [Fact]
        public void SeoKeywordsForSitePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoKeywordsForSiteRequest? seoKeywordsForSiteRequest = null;
            //var response = instance.SeoKeywordsForSitePost(seoKeywordsForSiteRequest);
            //Assert.IsType<SeoKeywordsForSitePost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsHistoryPost
        /// </summary>
        [Fact]
        public void SeoKeywordsHistoryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoKeywordHistoryRequest? seoKeywordHistoryRequest = null;
            //var response = instance.SeoKeywordsHistoryPost(seoKeywordHistoryRequest);
            //Assert.IsType<SeoKeywordsHistoryPost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsIdeasPost
        /// </summary>
        [Fact]
        public void SeoKeywordsIdeasPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoKeywordIdeasRequest? seoKeywordIdeasRequest = null;
            //var response = instance.SeoKeywordsIdeasPost(seoKeywordIdeasRequest);
            //Assert.IsType<SeoKeywordsIdeasPost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsIntentPost
        /// </summary>
        [Fact]
        public void SeoKeywordsIntentPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoKeywordIntentRequest? seoKeywordIntentRequest = null;
            //var response = instance.SeoKeywordsIntentPost(seoKeywordIntentRequest);
            //Assert.IsType<SeoKeywordsIntentPost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsOverviewPost
        /// </summary>
        [Fact]
        public void SeoKeywordsOverviewPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoKeywordOverviewRequest? seoKeywordOverviewRequest = null;
            //var response = instance.SeoKeywordsOverviewPost(seoKeywordOverviewRequest);
            //Assert.IsType<SeoKeywordsOverviewPost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsRelatedPost
        /// </summary>
        [Fact]
        public void SeoKeywordsRelatedPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoRelatedKeywordsRequest? seoRelatedKeywordsRequest = null;
            //var response = instance.SeoKeywordsRelatedPost(seoRelatedKeywordsRequest);
            //Assert.IsType<SeoKeywordsRelatedPost200Response>(response);
        }

        /// <summary>
        /// Test SeoKeywordsSuggestionsPost
        /// </summary>
        [Fact]
        public void SeoKeywordsSuggestionsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoKeywordSuggestionsRequest? seoKeywordSuggestionsRequest = null;
            //var response = instance.SeoKeywordsSuggestionsPost(seoKeywordSuggestionsRequest);
            //Assert.IsType<SeoKeywordsSuggestionsPost200Response>(response);
        }

        /// <summary>
        /// Test SeoSerpPost
        /// </summary>
        [Fact]
        public void SeoSerpPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeoSerpRequest? seoSerpRequest = null;
            //var response = instance.SeoSerpPost(seoSerpRequest);
            //Assert.IsType<SeoSerpPost200Response>(response);
        }
    }
}
