/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// A top-level comment on a TikTok video. Replies are fetched via /tiktok/videos/{id}/comments/{comment_id}/replies.
    /// </summary>
    [DataContract(Name = "Comment")]
    public partial class Comment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Comment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Comment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Comment" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="videoId">videoId (required).</param>
        /// <param name="text">text (required).</param>
        /// <param name="createTime">createTime (required).</param>
        /// <param name="likeCount">likeCount (required).</param>
        /// <param name="replyCount">replyCount (required).</param>
        /// <param name="isAuthorLiked">isAuthorLiked (required).</param>
        /// <param name="author">author (required).</param>
        public Comment(string id = default(string), string videoId = default(string), string text = default(string), int createTime = default(int), int likeCount = default(int), int replyCount = default(int), bool isAuthorLiked = default(bool), Author author = default(Author))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Comment and cannot be null");
            }
            this.Id = id;
            // to ensure "videoId" is required (not null)
            if (videoId == null)
            {
                throw new ArgumentNullException("videoId is a required property for Comment and cannot be null");
            }
            this.VideoId = videoId;
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for Comment and cannot be null");
            }
            this.Text = text;
            this.CreateTime = createTime;
            this.LikeCount = likeCount;
            this.ReplyCount = replyCount;
            this.IsAuthorLiked = isAuthorLiked;
            // to ensure "author" is required (not null)
            if (author == null)
            {
                throw new ArgumentNullException("author is a required property for Comment and cannot be null");
            }
            this.Author = author;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets VideoId
        /// </summary>
        [DataMember(Name = "video_id", IsRequired = true, EmitDefaultValue = true)]
        public string VideoId { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets CreateTime
        /// </summary>
        [DataMember(Name = "create_time", IsRequired = true, EmitDefaultValue = true)]
        public int CreateTime { get; set; }

        /// <summary>
        /// Gets or Sets LikeCount
        /// </summary>
        [DataMember(Name = "like_count", IsRequired = true, EmitDefaultValue = true)]
        public int LikeCount { get; set; }

        /// <summary>
        /// Gets or Sets ReplyCount
        /// </summary>
        [DataMember(Name = "reply_count", IsRequired = true, EmitDefaultValue = true)]
        public int ReplyCount { get; set; }

        /// <summary>
        /// Gets or Sets IsAuthorLiked
        /// </summary>
        [DataMember(Name = "is_author_liked", IsRequired = true, EmitDefaultValue = true)]
        public bool IsAuthorLiked { get; set; }

        /// <summary>
        /// Gets or Sets Author
        /// </summary>
        [DataMember(Name = "author", IsRequired = true, EmitDefaultValue = true)]
        public Author Author { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Comment {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  VideoId: ").Append(VideoId).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  LikeCount: ").Append(LikeCount).Append("\n");
            sb.Append("  ReplyCount: ").Append(ReplyCount).Append("\n");
            sb.Append("  IsAuthorLiked: ").Append(IsAuthorLiked).Append("\n");
            sb.Append("  Author: ").Append(Author).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) minLength
            if (this.Id != null && this.Id.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Id, length must be greater than 1.", new [] { "Id" });
            }

            yield break;
        }
    }

}
