/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// DataForSeoOrderByRule
    /// </summary>
    [DataContract(Name = "DataForSeoOrderByRule")]
    public partial class DataForSeoOrderByRule : IValidatableObject
    {
        /// <summary>
        /// Sort direction: asc or desc. Defaults to desc.
        /// </summary>
        /// <value>Sort direction: asc or desc. Defaults to desc.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DirEnum
        {
            /// <summary>
            /// Enum Asc for value: asc
            /// </summary>
            [EnumMember(Value = "asc")]
            Asc = 1,

            /// <summary>
            /// Enum Desc for value: desc
            /// </summary>
            [EnumMember(Value = "desc")]
            Desc = 2
        }


        /// <summary>
        /// Sort direction: asc or desc. Defaults to desc.
        /// </summary>
        /// <value>Sort direction: asc or desc. Defaults to desc.</value>
        [DataMember(Name = "dir", EmitDefaultValue = false)]
        public DirEnum? Dir { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataForSeoOrderByRule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DataForSeoOrderByRule()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataForSeoOrderByRule" /> class.
        /// </summary>
        /// <param name="field">Field to sort by. See the endpoint&#39;s list of sortable fields. (required).</param>
        /// <param name="dir">Sort direction: asc or desc. Defaults to desc. (default to DirEnum.Desc).</param>
        public DataForSeoOrderByRule(string field = default(string), DirEnum? dir = DirEnum.Desc)
        {
            // to ensure "field" is required (not null)
            if (field == null)
            {
                throw new ArgumentNullException("field is a required property for DataForSeoOrderByRule and cannot be null");
            }
            this.Field = field;
            this.Dir = dir;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Field to sort by. See the endpoint&#39;s list of sortable fields.
        /// </summary>
        /// <value>Field to sort by. See the endpoint&#39;s list of sortable fields.</value>
        [DataMember(Name = "field", IsRequired = true, EmitDefaultValue = true)]
        public string Field { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataForSeoOrderByRule {\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Dir: ").Append(Dir).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Field (string) minLength
            if (this.Field != null && this.Field.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Field, length must be greater than 1.", new [] { "Field" });
            }

            yield break;
        }
    }

}
