/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// Error
    /// </summary>
    [DataContract(Name = "Error")]
    public partial class Error : IValidatableObject
    {
        /// <summary>
        /// Closed vocabulary - see docs/adr/0003-error-model.md.
        /// </summary>
        /// <value>Closed vocabulary - see docs/adr/0003-error-model.md.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum ValidationError for value: validation_error
            /// </summary>
            [EnumMember(Value = "validation_error")]
            ValidationError = 1,

            /// <summary>
            /// Enum InvalidId for value: invalid_id
            /// </summary>
            [EnumMember(Value = "invalid_id")]
            InvalidId = 2,

            /// <summary>
            /// Enum InsufficientCredits for value: insufficient_credits
            /// </summary>
            [EnumMember(Value = "insufficient_credits")]
            InsufficientCredits = 3,

            /// <summary>
            /// Enum Unauthorized for value: unauthorized
            /// </summary>
            [EnumMember(Value = "unauthorized")]
            Unauthorized = 4,

            /// <summary>
            /// Enum NotFound for value: not_found
            /// </summary>
            [EnumMember(Value = "not_found")]
            NotFound = 5,

            /// <summary>
            /// Enum RateLimited for value: rate_limited
            /// </summary>
            [EnumMember(Value = "rate_limited")]
            RateLimited = 6,

            /// <summary>
            /// Enum InternalError for value: internal_error
            /// </summary>
            [EnumMember(Value = "internal_error")]
            InternalError = 7,

            /// <summary>
            /// Enum ResponseShapeError for value: response_shape_error
            /// </summary>
            [EnumMember(Value = "response_shape_error")]
            ResponseShapeError = 8,

            /// <summary>
            /// Enum UpstreamError for value: upstream_error
            /// </summary>
            [EnumMember(Value = "upstream_error")]
            UpstreamError = 9,

            /// <summary>
            /// Enum UpstreamUnavailable for value: upstream_unavailable
            /// </summary>
            [EnumMember(Value = "upstream_unavailable")]
            UpstreamUnavailable = 10
        }


        /// <summary>
        /// Closed vocabulary - see docs/adr/0003-error-model.md.
        /// </summary>
        /// <value>Closed vocabulary - see docs/adr/0003-error-model.md.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Error" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Error() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Error" /> class.
        /// </summary>
        /// <param name="type">Closed vocabulary - see docs/adr/0003-error-model.md. (required).</param>
        /// <param name="message">message (required).</param>
        /// <param name="requestId">UnifAPI request id, e.g. &#x60;unif_&lt;id&gt;&#x60;. Source ids are not exposed..</param>
        /// <param name="issues">Present only when type&#x3D;validation_error..</param>
        /// <param name="billing">billing.</param>
        public Error(TypeEnum type = default(TypeEnum), string message = default(string), string requestId = default(string), List<Object> issues = default(List<Object>), ErrorBilling billing = default(ErrorBilling))
        {
            this.Type = type;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for Error and cannot be null");
            }
            this.Message = message;
            this.RequestId = requestId;
            this.Issues = issues;
            this.Billing = billing;
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// UnifAPI request id, e.g. &#x60;unif_&lt;id&gt;&#x60;. Source ids are not exposed.
        /// </summary>
        /// <value>UnifAPI request id, e.g. &#x60;unif_&lt;id&gt;&#x60;. Source ids are not exposed.</value>
        [DataMember(Name = "request_id", EmitDefaultValue = false)]
        public string RequestId { get; set; }

        /// <summary>
        /// Present only when type&#x3D;validation_error.
        /// </summary>
        /// <value>Present only when type&#x3D;validation_error.</value>
        [DataMember(Name = "issues", EmitDefaultValue = false)]
        public List<Object> Issues { get; set; }

        /// <summary>
        /// Gets or Sets Billing
        /// </summary>
        [DataMember(Name = "billing", EmitDefaultValue = false)]
        public ErrorBilling Billing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Error {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  Issues: ").Append(Issues).Append("\n");
            sb.Append("  Billing: ").Append(Billing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
