/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// GeoKeywordSearchVolumeResponse
    /// </summary>
    [DataContract(Name = "GeoKeywordSearchVolumeResponse")]
    public partial class GeoKeywordSearchVolumeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoKeywordSearchVolumeResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GeoKeywordSearchVolumeResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoKeywordSearchVolumeResponse" /> class.
        /// </summary>
        /// <param name="location">location (required).</param>
        /// <param name="language">language (required).</param>
        /// <param name="results">One billable record per keyword with AI search volume and monthly trend. (required).</param>
        public GeoKeywordSearchVolumeResponse(string location = default(string), string language = default(string), List<GeoKeywordSearchVolumeRecord> results = default(List<GeoKeywordSearchVolumeRecord>))
        {
            // to ensure "location" is required (not null)
            if (location == null)
            {
                throw new ArgumentNullException("location is a required property for GeoKeywordSearchVolumeResponse and cannot be null");
            }
            this.Location = location;
            // to ensure "language" is required (not null)
            if (language == null)
            {
                throw new ArgumentNullException("language is a required property for GeoKeywordSearchVolumeResponse and cannot be null");
            }
            this.Language = language;
            // to ensure "results" is required (not null)
            if (results == null)
            {
                throw new ArgumentNullException("results is a required property for GeoKeywordSearchVolumeResponse and cannot be null");
            }
            this.Results = results;
        }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", IsRequired = true, EmitDefaultValue = true)]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name = "language", IsRequired = true, EmitDefaultValue = true)]
        public string Language { get; set; }

        /// <summary>
        /// One billable record per keyword with AI search volume and monthly trend.
        /// </summary>
        /// <value>One billable record per keyword with AI search volume and monthly trend.</value>
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<GeoKeywordSearchVolumeRecord> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoKeywordSearchVolumeResponse {\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
