/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// GeoMentionsSearchResponse
    /// </summary>
    [DataContract(Name = "GeoMentionsSearchResponse")]
    public partial class GeoMentionsSearchResponse : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Engine
        /// </summary>
        [DataMember(Name = "engine", IsRequired = true, EmitDefaultValue = true)]
        public GeoEngine Engine { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoMentionsSearchResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GeoMentionsSearchResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoMentionsSearchResponse" /> class.
        /// </summary>
        /// <param name="engine">engine (required).</param>
        /// <param name="location">location (required).</param>
        /// <param name="language">language (required).</param>
        /// <param name="totalCount">Total mentions matching the request..</param>
        /// <param name="returnedCount">Mentions returned in results. (required).</param>
        /// <param name="cursor">search_after_token for the next page, when more remain..</param>
        /// <param name="results">One billable record per matched mention. (required).</param>
        public GeoMentionsSearchResponse(GeoEngine engine = default(GeoEngine), string location = default(string), string language = default(string), int totalCount = default(int), int returnedCount = default(int), string cursor = default(string), List<GeoMentionRecord> results = default(List<GeoMentionRecord>))
        {
            this.Engine = engine;
            // to ensure "location" is required (not null)
            if (location == null)
            {
                throw new ArgumentNullException("location is a required property for GeoMentionsSearchResponse and cannot be null");
            }
            this.Location = location;
            // to ensure "language" is required (not null)
            if (language == null)
            {
                throw new ArgumentNullException("language is a required property for GeoMentionsSearchResponse and cannot be null");
            }
            this.Language = language;
            this.ReturnedCount = returnedCount;
            // to ensure "results" is required (not null)
            if (results == null)
            {
                throw new ArgumentNullException("results is a required property for GeoMentionsSearchResponse and cannot be null");
            }
            this.Results = results;
            this.TotalCount = totalCount;
            this.Cursor = cursor;
        }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", IsRequired = true, EmitDefaultValue = true)]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name = "language", IsRequired = true, EmitDefaultValue = true)]
        public string Language { get; set; }

        /// <summary>
        /// Total mentions matching the request.
        /// </summary>
        /// <value>Total mentions matching the request.</value>
        [DataMember(Name = "total_count", EmitDefaultValue = false)]
        public int TotalCount { get; set; }

        /// <summary>
        /// Mentions returned in results.
        /// </summary>
        /// <value>Mentions returned in results.</value>
        [DataMember(Name = "returned_count", IsRequired = true, EmitDefaultValue = true)]
        public int ReturnedCount { get; set; }

        /// <summary>
        /// search_after_token for the next page, when more remain.
        /// </summary>
        /// <value>search_after_token for the next page, when more remain.</value>
        [DataMember(Name = "cursor", EmitDefaultValue = false)]
        public string Cursor { get; set; }

        /// <summary>
        /// One billable record per matched mention.
        /// </summary>
        /// <value>One billable record per matched mention.</value>
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<GeoMentionRecord> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoMentionsSearchResponse {\n");
            sb.Append("  Engine: ").Append(Engine).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  ReturnedCount: ").Append(ReturnedCount).Append("\n");
            sb.Append("  Cursor: ").Append(Cursor).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
