/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// GeoMentionsAggregatedMetricsRequestFiltersAnyOf
    /// </summary>
    [DataContract(Name = "GeoMentionsAggregatedMetricsRequest_filters_anyOf")]
    public partial class GeoMentionsAggregatedMetricsRequestFiltersAnyOf : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoMentionsAggregatedMetricsRequestFiltersAnyOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GeoMentionsAggregatedMetricsRequestFiltersAnyOf()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoMentionsAggregatedMetricsRequestFiltersAnyOf" /> class.
        /// </summary>
        /// <param name="and">Sub-expressions that must all match. (required).</param>
        public GeoMentionsAggregatedMetricsRequestFiltersAnyOf(List<DataForSeoFilter> and = default(List<DataForSeoFilter>))
        {
            // to ensure "and" is required (not null)
            if (and == null)
            {
                throw new ArgumentNullException("and is a required property for GeoMentionsAggregatedMetricsRequestFiltersAnyOf and cannot be null");
            }
            this.And = and;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Sub-expressions that must all match.
        /// </summary>
        /// <value>Sub-expressions that must all match.</value>
        [DataMember(Name = "and", IsRequired = true, EmitDefaultValue = true)]
        public List<DataForSeoFilter> And { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoMentionsAggregatedMetricsRequestFiltersAnyOf {\n");
            sb.Append("  And: ").Append(And).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
