/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// Filter the matched mentions. Provide a single condition {\&quot;field\&quot;,\&quot;op\&quot;,\&quot;value\&quot;} or an {\&quot;and\&quot;:[…]} / {\&quot;or\&quot;:[…]} group of conditions (nest groups for mixed logic), up to 8 conditions. Operators: &#x3D;, &lt;&gt;, &lt;, &lt;&#x3D;, &gt;, &gt;&#x3D;, in, not_in, like, not_like, ilike, not_ilike, match, not_match (use an array value with in / not_in). Filterable fields: ai_search_volume (monthly AI search volume); platform (LLM engine, e.g. chat_gpt, google, perplexity); model (model name that produced the answer). Example: {\&quot;and\&quot;:[{\&quot;field\&quot;:\&quot;ai_search_volume\&quot;,\&quot;op\&quot;:\&quot;&gt;\&quot;,\&quot;value\&quot;:1000},{\&quot;field\&quot;:\&quot;platform\&quot;,\&quot;op\&quot;:\&quot;&#x3D;\&quot;,\&quot;value\&quot;:\&quot;chat_gpt\&quot;}]}
    /// </summary>
    [JsonConverter(typeof(GeoMentionsSearchRequestFiltersJsonConverter))]
    [DataContract(Name = "GeoMentionsSearchRequest_filters")]
    public partial class GeoMentionsSearchRequestFilters : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoMentionsSearchRequestFilters" /> class
        /// with the <see cref="DataForSeoFilterCondition" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DataForSeoFilterCondition.</param>
        public GeoMentionsSearchRequestFilters(DataForSeoFilterCondition actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeoMentionsSearchRequestFilters" /> class
        /// with the <see cref="GeoMentionsAggregatedMetricsRequestFiltersAnyOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of GeoMentionsAggregatedMetricsRequestFiltersAnyOf.</param>
        public GeoMentionsSearchRequestFilters(GeoMentionsAggregatedMetricsRequestFiltersAnyOf actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeoMentionsSearchRequestFilters" /> class
        /// with the <see cref="GeoMentionsAggregatedMetricsRequestFiltersAnyOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of GeoMentionsAggregatedMetricsRequestFiltersAnyOf1.</param>
        public GeoMentionsSearchRequestFilters(GeoMentionsAggregatedMetricsRequestFiltersAnyOf1 actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(DataForSeoFilterCondition))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(GeoMentionsAggregatedMetricsRequestFiltersAnyOf))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(GeoMentionsAggregatedMetricsRequestFiltersAnyOf1))
                {
                    _actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: DataForSeoFilterCondition, GeoMentionsAggregatedMetricsRequestFiltersAnyOf, GeoMentionsAggregatedMetricsRequestFiltersAnyOf1");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `DataForSeoFilterCondition`. If the actual instance is not `DataForSeoFilterCondition`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DataForSeoFilterCondition</returns>
        public DataForSeoFilterCondition GetDataForSeoFilterCondition()
        {
            return (DataForSeoFilterCondition)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `GeoMentionsAggregatedMetricsRequestFiltersAnyOf`. If the actual instance is not `GeoMentionsAggregatedMetricsRequestFiltersAnyOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of GeoMentionsAggregatedMetricsRequestFiltersAnyOf</returns>
        public GeoMentionsAggregatedMetricsRequestFiltersAnyOf GetGeoMentionsAggregatedMetricsRequestFiltersAnyOf()
        {
            return (GeoMentionsAggregatedMetricsRequestFiltersAnyOf)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `GeoMentionsAggregatedMetricsRequestFiltersAnyOf1`. If the actual instance is not `GeoMentionsAggregatedMetricsRequestFiltersAnyOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of GeoMentionsAggregatedMetricsRequestFiltersAnyOf1</returns>
        public GeoMentionsAggregatedMetricsRequestFiltersAnyOf1 GetGeoMentionsAggregatedMetricsRequestFiltersAnyOf1()
        {
            return (GeoMentionsAggregatedMetricsRequestFiltersAnyOf1)ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GeoMentionsSearchRequestFilters {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, GeoMentionsSearchRequestFilters.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of GeoMentionsSearchRequestFilters
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of GeoMentionsSearchRequestFilters</returns>
        public static GeoMentionsSearchRequestFilters FromJson(string jsonString)
        {
            GeoMentionsSearchRequestFilters newGeoMentionsSearchRequestFilters = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newGeoMentionsSearchRequestFilters;
            }

            try
            {
                newGeoMentionsSearchRequestFilters = new GeoMentionsSearchRequestFilters(JsonConvert.DeserializeObject<DataForSeoFilterCondition>(jsonString, GeoMentionsSearchRequestFilters.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newGeoMentionsSearchRequestFilters;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DataForSeoFilterCondition: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newGeoMentionsSearchRequestFilters = new GeoMentionsSearchRequestFilters(JsonConvert.DeserializeObject<GeoMentionsAggregatedMetricsRequestFiltersAnyOf>(jsonString, GeoMentionsSearchRequestFilters.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newGeoMentionsSearchRequestFilters;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into GeoMentionsAggregatedMetricsRequestFiltersAnyOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newGeoMentionsSearchRequestFilters = new GeoMentionsSearchRequestFilters(JsonConvert.DeserializeObject<GeoMentionsAggregatedMetricsRequestFiltersAnyOf1>(jsonString, GeoMentionsSearchRequestFilters.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newGeoMentionsSearchRequestFilters;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into GeoMentionsAggregatedMetricsRequestFiltersAnyOf1: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for GeoMentionsSearchRequestFilters
    /// </summary>
    public class GeoMentionsSearchRequestFiltersJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(GeoMentionsSearchRequestFilters).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return GeoMentionsSearchRequestFilters.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return GeoMentionsSearchRequestFilters.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
