/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// GeoSerpRequest
    /// </summary>
    [DataContract(Name = "GeoSerpRequest")]
    public partial class GeoSerpRequest : IValidatableObject
    {
        /// <summary>
        /// AI SERP device type. Defaults to desktop.
        /// </summary>
        /// <value>AI SERP device type. Defaults to desktop.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DeviceEnum
        {
            /// <summary>
            /// Enum Desktop for value: desktop
            /// </summary>
            [EnumMember(Value = "desktop")]
            Desktop = 1,

            /// <summary>
            /// Enum Mobile for value: mobile
            /// </summary>
            [EnumMember(Value = "mobile")]
            Mobile = 2
        }


        /// <summary>
        /// AI SERP device type. Defaults to desktop.
        /// </summary>
        /// <value>AI SERP device type. Defaults to desktop.</value>
        [DataMember(Name = "device", EmitDefaultValue = false)]
        public DeviceEnum? Device { get; set; }

        /// <summary>
        /// Gets or Sets View
        /// </summary>
        [DataMember(Name = "view", EmitDefaultValue = false)]
        public GeoSerpView? View { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoSerpRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GeoSerpRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoSerpRequest" /> class.
        /// </summary>
        /// <param name="query">Search query to inspect in AI Mode. (required).</param>
        /// <param name="target">Optional domain or URL to mark when it appears in AI Mode answers, links, or cited references..</param>
        /// <param name="location">location.</param>
        /// <param name="language">Search language as an ISO code or full language name. Defaults to en..</param>
        /// <param name="device">AI SERP device type. Defaults to desktop..</param>
        /// <param name="includePixelRankings">When true, request pixel rectangle data for visual AI SERP analysis..</param>
        /// <param name="view">view.</param>
        public GeoSerpRequest(string query = default(string), string target = default(string), GeoSerpLocation location = default(GeoSerpLocation), string language = default(string), DeviceEnum? device = default(DeviceEnum?), bool includePixelRankings = default(bool), GeoSerpView? view = default(GeoSerpView?))
        {
            // to ensure "query" is required (not null)
            if (query == null)
            {
                throw new ArgumentNullException("query is a required property for GeoSerpRequest and cannot be null");
            }
            this.Query = query;
            this.Target = target;
            this.Location = location;
            this.Language = language;
            this.Device = device;
            this.IncludePixelRankings = includePixelRankings;
            this.View = view;
        }

        /// <summary>
        /// Search query to inspect in AI Mode.
        /// </summary>
        /// <value>Search query to inspect in AI Mode.</value>
        [DataMember(Name = "query", IsRequired = true, EmitDefaultValue = true)]
        public string Query { get; set; }

        /// <summary>
        /// Optional domain or URL to mark when it appears in AI Mode answers, links, or cited references.
        /// </summary>
        /// <value>Optional domain or URL to mark when it appears in AI Mode answers, links, or cited references.</value>
        [DataMember(Name = "target", EmitDefaultValue = false)]
        public string Target { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", EmitDefaultValue = false)]
        public GeoSerpLocation Location { get; set; }

        /// <summary>
        /// Search language as an ISO code or full language name. Defaults to en.
        /// </summary>
        /// <value>Search language as an ISO code or full language name. Defaults to en.</value>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language { get; set; }

        /// <summary>
        /// When true, request pixel rectangle data for visual AI SERP analysis.
        /// </summary>
        /// <value>When true, request pixel rectangle data for visual AI SERP analysis.</value>
        [DataMember(Name = "include_pixel_rankings", EmitDefaultValue = true)]
        public bool IncludePixelRankings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoSerpRequest {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("  IncludePixelRankings: ").Append(IncludePixelRankings).Append("\n");
            sb.Append("  View: ").Append(View).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Query (string) maxLength
            if (this.Query != null && this.Query.Length > 700)
            {
                yield return new ValidationResult("Invalid value for Query, length must be less than 700.", new [] { "Query" });
            }

            // Query (string) minLength
            if (this.Query != null && this.Query.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Query, length must be greater than 1.", new [] { "Query" });
            }

            // Target (string) minLength
            if (this.Target != null && this.Target.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Target, length must be greater than 1.", new [] { "Target" });
            }

            // Language (string) maxLength
            if (this.Language != null && this.Language.Length > 80)
            {
                yield return new ValidationResult("Invalid value for Language, length must be less than 80.", new [] { "Language" });
            }

            // Language (string) minLength
            if (this.Language != null && this.Language.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Language, length must be greater than 2.", new [] { "Language" });
            }

            yield break;
        }
    }

}
