/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// Hotel location details when present.
    /// </summary>
    [DataContract(Name = "HotelPlace")]
    public partial class HotelPlace : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HotelPlace" /> class.
        /// </summary>
        /// <param name="neighborhood">Neighborhood where the hotel is located..</param>
        /// <param name="neighborhoodDescription">neighborhoodDescription.</param>
        /// <param name="mapsUrl">Google Maps URL for the hotel location..</param>
        /// <param name="overallScore">Overall location score from 1 to 5..</param>
        /// <param name="scoreByCategories">Location sub-scores by category, such as transit or things_to_do..</param>
        /// <param name="latitude">Latitude of the hotel on Google Maps..</param>
        /// <param name="longitude">Longitude of the hotel on Google Maps..</param>
        /// <param name="extras">extras.</param>
        public HotelPlace(string neighborhood = default(string), string neighborhoodDescription = default(string), string mapsUrl = default(string), decimal overallScore = default(decimal), Dictionary<string, decimal> scoreByCategories = default(Dictionary<string, decimal>), decimal latitude = default(decimal), decimal longitude = default(decimal), Dictionary extras = default(Dictionary))
        {
            this.Neighborhood = neighborhood;
            this.NeighborhoodDescription = neighborhoodDescription;
            this.MapsUrl = mapsUrl;
            this.OverallScore = overallScore;
            this.ScoreByCategories = scoreByCategories;
            this.Latitude = latitude;
            this.Longitude = longitude;
            this.Extras = extras;
        }

        /// <summary>
        /// Neighborhood where the hotel is located.
        /// </summary>
        /// <value>Neighborhood where the hotel is located.</value>
        [DataMember(Name = "neighborhood", EmitDefaultValue = false)]
        public string Neighborhood { get; set; }

        /// <summary>
        /// Gets or Sets NeighborhoodDescription
        /// </summary>
        [DataMember(Name = "neighborhood_description", EmitDefaultValue = false)]
        public string NeighborhoodDescription { get; set; }

        /// <summary>
        /// Google Maps URL for the hotel location.
        /// </summary>
        /// <value>Google Maps URL for the hotel location.</value>
        [DataMember(Name = "maps_url", EmitDefaultValue = false)]
        public string MapsUrl { get; set; }

        /// <summary>
        /// Overall location score from 1 to 5.
        /// </summary>
        /// <value>Overall location score from 1 to 5.</value>
        [DataMember(Name = "overall_score", EmitDefaultValue = false)]
        public decimal OverallScore { get; set; }

        /// <summary>
        /// Location sub-scores by category, such as transit or things_to_do.
        /// </summary>
        /// <value>Location sub-scores by category, such as transit or things_to_do.</value>
        [DataMember(Name = "score_by_categories", EmitDefaultValue = false)]
        public Dictionary<string, decimal> ScoreByCategories { get; set; }

        /// <summary>
        /// Latitude of the hotel on Google Maps.
        /// </summary>
        /// <value>Latitude of the hotel on Google Maps.</value>
        [DataMember(Name = "latitude", EmitDefaultValue = false)]
        public decimal Latitude { get; set; }

        /// <summary>
        /// Longitude of the hotel on Google Maps.
        /// </summary>
        /// <value>Longitude of the hotel on Google Maps.</value>
        [DataMember(Name = "longitude", EmitDefaultValue = false)]
        public decimal Longitude { get; set; }

        /// <summary>
        /// Gets or Sets Extras
        /// </summary>
        [DataMember(Name = "extras", EmitDefaultValue = false)]
        public Dictionary Extras { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HotelPlace {\n");
            sb.Append("  Neighborhood: ").Append(Neighborhood).Append("\n");
            sb.Append("  NeighborhoodDescription: ").Append(NeighborhoodDescription).Append("\n");
            sb.Append("  MapsUrl: ").Append(MapsUrl).Append("\n");
            sb.Append("  OverallScore: ").Append(OverallScore).Append("\n");
            sb.Append("  ScoreByCategories: ").Append(ScoreByCategories).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  Extras: ").Append(Extras).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
