/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// InstagramPost
    /// </summary>
    [DataContract(Name = "InstagramPost")]
    public partial class InstagramPost : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstagramPost" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InstagramPost() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InstagramPost" /> class.
        /// </summary>
        /// <param name="id">Instagram URL slug (&#x60;shortcode&#x60;). Path parameter for /instagram/posts/{id}/... endpoints. (required).</param>
        /// <param name="shortcode">shortcode (required).</param>
        /// <param name="mediaId">mediaId (required).</param>
        /// <param name="mediaType">Source media_type: 1 &#x3D; image, 2 &#x3D; video, 8 &#x3D; carousel (required).</param>
        /// <param name="productType">Source product_type: &#39;feed&#39; (image/photo), &#39;clips&#39; (reel), &#39;carousel_container&#39;, &#39;igtv&#39;, etc. (required).</param>
        /// <param name="takenAt">Unix-seconds timestamp. (required).</param>
        /// <param name="caption">caption (required).</param>
        /// <param name="accessibilityCaption">accessibilityCaption (required).</param>
        /// <param name="imageUrl">Largest available preview image (cover, for video/carousel). (required).</param>
        /// <param name="videoUrl">Highest-quality video URL when applicable; empty string otherwise. (required).</param>
        /// <param name="likeCount">likeCount (required).</param>
        /// <param name="commentCount">commentCount (required).</param>
        /// <param name="playCount">Video plays. 0 for non-video media. (required).</param>
        /// <param name="viewCount">Reel/video views (separate from plays on IG side). 0 when N/A. (required).</param>
        /// <param name="isPaidPartnership">isPaidPartnership (required).</param>
        /// <param name="hasAudio">hasAudio (required).</param>
        /// <param name="carouselCount">Number of carousel items, or 0 if not a carousel. (required).</param>
        /// <param name="carousel">Carousel items when media_type &#x3D;&#x3D;&#x3D; 8; empty array otherwise. (required).</param>
        /// <param name="user">user (required).</param>
        /// <param name="location">location (required).</param>
        public InstagramPost(string id = default(string), string shortcode = default(string), string mediaId = default(string), decimal mediaType = default(decimal), string productType = default(string), decimal takenAt = default(decimal), string caption = default(string), string accessibilityCaption = default(string), string imageUrl = default(string), string videoUrl = default(string), decimal likeCount = default(decimal), decimal commentCount = default(decimal), decimal playCount = default(decimal), decimal viewCount = default(decimal), bool isPaidPartnership = default(bool), bool hasAudio = default(bool), decimal carouselCount = default(decimal), List<InstagramCarouselItem> carousel = default(List<InstagramCarouselItem>), InstagramUserPreview user = default(InstagramUserPreview), InstagramLocationLite location = default(InstagramLocationLite))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for InstagramPost and cannot be null");
            }
            this.Id = id;
            // to ensure "shortcode" is required (not null)
            if (shortcode == null)
            {
                throw new ArgumentNullException("shortcode is a required property for InstagramPost and cannot be null");
            }
            this.Shortcode = shortcode;
            // to ensure "mediaId" is required (not null)
            if (mediaId == null)
            {
                throw new ArgumentNullException("mediaId is a required property for InstagramPost and cannot be null");
            }
            this.MediaId = mediaId;
            this.MediaType = mediaType;
            // to ensure "productType" is required (not null)
            if (productType == null)
            {
                throw new ArgumentNullException("productType is a required property for InstagramPost and cannot be null");
            }
            this.ProductType = productType;
            this.TakenAt = takenAt;
            // to ensure "caption" is required (not null)
            if (caption == null)
            {
                throw new ArgumentNullException("caption is a required property for InstagramPost and cannot be null");
            }
            this.Caption = caption;
            // to ensure "accessibilityCaption" is required (not null)
            if (accessibilityCaption == null)
            {
                throw new ArgumentNullException("accessibilityCaption is a required property for InstagramPost and cannot be null");
            }
            this.AccessibilityCaption = accessibilityCaption;
            // to ensure "imageUrl" is required (not null)
            if (imageUrl == null)
            {
                throw new ArgumentNullException("imageUrl is a required property for InstagramPost and cannot be null");
            }
            this.ImageUrl = imageUrl;
            // to ensure "videoUrl" is required (not null)
            if (videoUrl == null)
            {
                throw new ArgumentNullException("videoUrl is a required property for InstagramPost and cannot be null");
            }
            this.VideoUrl = videoUrl;
            this.LikeCount = likeCount;
            this.CommentCount = commentCount;
            this.PlayCount = playCount;
            this.ViewCount = viewCount;
            this.IsPaidPartnership = isPaidPartnership;
            this.HasAudio = hasAudio;
            this.CarouselCount = carouselCount;
            // to ensure "carousel" is required (not null)
            if (carousel == null)
            {
                throw new ArgumentNullException("carousel is a required property for InstagramPost and cannot be null");
            }
            this.Carousel = carousel;
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for InstagramPost and cannot be null");
            }
            this.User = user;
            // to ensure "location" is required (not null)
            if (location == null)
            {
                throw new ArgumentNullException("location is a required property for InstagramPost and cannot be null");
            }
            this.Location = location;
        }

        /// <summary>
        /// Instagram URL slug (&#x60;shortcode&#x60;). Path parameter for /instagram/posts/{id}/... endpoints.
        /// </summary>
        /// <value>Instagram URL slug (&#x60;shortcode&#x60;). Path parameter for /instagram/posts/{id}/... endpoints.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Shortcode
        /// </summary>
        [DataMember(Name = "shortcode", IsRequired = true, EmitDefaultValue = true)]
        public string Shortcode { get; set; }

        /// <summary>
        /// Gets or Sets MediaId
        /// </summary>
        [DataMember(Name = "media_id", IsRequired = true, EmitDefaultValue = true)]
        public string MediaId { get; set; }

        /// <summary>
        /// Source media_type: 1 &#x3D; image, 2 &#x3D; video, 8 &#x3D; carousel
        /// </summary>
        /// <value>Source media_type: 1 &#x3D; image, 2 &#x3D; video, 8 &#x3D; carousel</value>
        [DataMember(Name = "media_type", IsRequired = true, EmitDefaultValue = true)]
        public decimal MediaType { get; set; }

        /// <summary>
        /// Source product_type: &#39;feed&#39; (image/photo), &#39;clips&#39; (reel), &#39;carousel_container&#39;, &#39;igtv&#39;, etc.
        /// </summary>
        /// <value>Source product_type: &#39;feed&#39; (image/photo), &#39;clips&#39; (reel), &#39;carousel_container&#39;, &#39;igtv&#39;, etc.</value>
        [DataMember(Name = "product_type", IsRequired = true, EmitDefaultValue = true)]
        public string ProductType { get; set; }

        /// <summary>
        /// Unix-seconds timestamp.
        /// </summary>
        /// <value>Unix-seconds timestamp.</value>
        [DataMember(Name = "taken_at", IsRequired = true, EmitDefaultValue = true)]
        public decimal TakenAt { get; set; }

        /// <summary>
        /// Gets or Sets Caption
        /// </summary>
        [DataMember(Name = "caption", IsRequired = true, EmitDefaultValue = true)]
        public string Caption { get; set; }

        /// <summary>
        /// Gets or Sets AccessibilityCaption
        /// </summary>
        [DataMember(Name = "accessibility_caption", IsRequired = true, EmitDefaultValue = true)]
        public string AccessibilityCaption { get; set; }

        /// <summary>
        /// Largest available preview image (cover, for video/carousel).
        /// </summary>
        /// <value>Largest available preview image (cover, for video/carousel).</value>
        [DataMember(Name = "image_url", IsRequired = true, EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Highest-quality video URL when applicable; empty string otherwise.
        /// </summary>
        /// <value>Highest-quality video URL when applicable; empty string otherwise.</value>
        [DataMember(Name = "video_url", IsRequired = true, EmitDefaultValue = true)]
        public string VideoUrl { get; set; }

        /// <summary>
        /// Gets or Sets LikeCount
        /// </summary>
        [DataMember(Name = "like_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal LikeCount { get; set; }

        /// <summary>
        /// Gets or Sets CommentCount
        /// </summary>
        [DataMember(Name = "comment_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal CommentCount { get; set; }

        /// <summary>
        /// Video plays. 0 for non-video media.
        /// </summary>
        /// <value>Video plays. 0 for non-video media.</value>
        [DataMember(Name = "play_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal PlayCount { get; set; }

        /// <summary>
        /// Reel/video views (separate from plays on IG side). 0 when N/A.
        /// </summary>
        /// <value>Reel/video views (separate from plays on IG side). 0 when N/A.</value>
        [DataMember(Name = "view_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal ViewCount { get; set; }

        /// <summary>
        /// Gets or Sets IsPaidPartnership
        /// </summary>
        [DataMember(Name = "is_paid_partnership", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPaidPartnership { get; set; }

        /// <summary>
        /// Gets or Sets HasAudio
        /// </summary>
        [DataMember(Name = "has_audio", IsRequired = true, EmitDefaultValue = true)]
        public bool HasAudio { get; set; }

        /// <summary>
        /// Number of carousel items, or 0 if not a carousel.
        /// </summary>
        /// <value>Number of carousel items, or 0 if not a carousel.</value>
        [DataMember(Name = "carousel_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal CarouselCount { get; set; }

        /// <summary>
        /// Carousel items when media_type &#x3D;&#x3D;&#x3D; 8; empty array otherwise.
        /// </summary>
        /// <value>Carousel items when media_type &#x3D;&#x3D;&#x3D; 8; empty array otherwise.</value>
        [DataMember(Name = "carousel", IsRequired = true, EmitDefaultValue = true)]
        public List<InstagramCarouselItem> Carousel { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public InstagramUserPreview User { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", IsRequired = true, EmitDefaultValue = true)]
        public InstagramLocationLite Location { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstagramPost {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Shortcode: ").Append(Shortcode).Append("\n");
            sb.Append("  MediaId: ").Append(MediaId).Append("\n");
            sb.Append("  MediaType: ").Append(MediaType).Append("\n");
            sb.Append("  ProductType: ").Append(ProductType).Append("\n");
            sb.Append("  TakenAt: ").Append(TakenAt).Append("\n");
            sb.Append("  Caption: ").Append(Caption).Append("\n");
            sb.Append("  AccessibilityCaption: ").Append(AccessibilityCaption).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  VideoUrl: ").Append(VideoUrl).Append("\n");
            sb.Append("  LikeCount: ").Append(LikeCount).Append("\n");
            sb.Append("  CommentCount: ").Append(CommentCount).Append("\n");
            sb.Append("  PlayCount: ").Append(PlayCount).Append("\n");
            sb.Append("  ViewCount: ").Append(ViewCount).Append("\n");
            sb.Append("  IsPaidPartnership: ").Append(IsPaidPartnership).Append("\n");
            sb.Append("  HasAudio: ").Append(HasAudio).Append("\n");
            sb.Append("  CarouselCount: ").Append(CarouselCount).Append("\n");
            sb.Append("  Carousel: ").Append(Carousel).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) minLength
            if (this.Id != null && this.Id.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Id, length must be greater than 1.", new [] { "Id" });
            }

            yield break;
        }
    }

}
