/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// InstagramResolveShortcodeGet200ResponseData
    /// </summary>
    [DataContract(Name = "_instagram_resolve_shortcode_get_200_response_data")]
    public partial class InstagramResolveShortcodeGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstagramResolveShortcodeGet200ResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InstagramResolveShortcodeGet200ResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InstagramResolveShortcodeGet200ResponseData" /> class.
        /// </summary>
        /// <param name="url">url (required).</param>
        /// <param name="shortcode">shortcode (required).</param>
        public InstagramResolveShortcodeGet200ResponseData(string url = default(string), string shortcode = default(string))
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for InstagramResolveShortcodeGet200ResponseData and cannot be null");
            }
            this.Url = url;
            // to ensure "shortcode" is required (not null)
            if (shortcode == null)
            {
                throw new ArgumentNullException("shortcode is a required property for InstagramResolveShortcodeGet200ResponseData and cannot be null");
            }
            this.Shortcode = shortcode;
        }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Shortcode
        /// </summary>
        [DataMember(Name = "shortcode", IsRequired = true, EmitDefaultValue = true)]
        public string Shortcode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstagramResolveShortcodeGet200ResponseData {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Shortcode: ").Append(Shortcode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
