/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// LinkedinAd
    /// </summary>
    [DataContract(Name = "LinkedinAd")]
    public partial class LinkedinAd : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinAd" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkedinAd() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinAd" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="content">content (required).</param>
        /// <param name="adUrl">adUrl (required).</param>
        /// <param name="imageUrl">imageUrl (required).</param>
        /// <param name="adType">adType (required).</param>
        /// <param name="paidForBy">paidForBy (required).</param>
        /// <param name="advertiser">advertiser (required).</param>
        /// <param name="publisher">publisher (required).</param>
        public LinkedinAd(string id = default(string), string content = default(string), string adUrl = default(string), string imageUrl = default(string), string adType = default(string), string paidForBy = default(string), LinkedinAdAdvertiser advertiser = default(LinkedinAdAdvertiser), LinkedinAdAdvertiser publisher = default(LinkedinAdAdvertiser))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for LinkedinAd and cannot be null");
            }
            this.Id = id;
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new ArgumentNullException("content is a required property for LinkedinAd and cannot be null");
            }
            this.Content = content;
            // to ensure "adUrl" is required (not null)
            if (adUrl == null)
            {
                throw new ArgumentNullException("adUrl is a required property for LinkedinAd and cannot be null");
            }
            this.AdUrl = adUrl;
            // to ensure "imageUrl" is required (not null)
            if (imageUrl == null)
            {
                throw new ArgumentNullException("imageUrl is a required property for LinkedinAd and cannot be null");
            }
            this.ImageUrl = imageUrl;
            // to ensure "adType" is required (not null)
            if (adType == null)
            {
                throw new ArgumentNullException("adType is a required property for LinkedinAd and cannot be null");
            }
            this.AdType = adType;
            // to ensure "paidForBy" is required (not null)
            if (paidForBy == null)
            {
                throw new ArgumentNullException("paidForBy is a required property for LinkedinAd and cannot be null");
            }
            this.PaidForBy = paidForBy;
            // to ensure "advertiser" is required (not null)
            if (advertiser == null)
            {
                throw new ArgumentNullException("advertiser is a required property for LinkedinAd and cannot be null");
            }
            this.Advertiser = advertiser;
            // to ensure "publisher" is required (not null)
            if (publisher == null)
            {
                throw new ArgumentNullException("publisher is a required property for LinkedinAd and cannot be null");
            }
            this.Publisher = publisher;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name = "content", IsRequired = true, EmitDefaultValue = true)]
        public string Content { get; set; }

        /// <summary>
        /// Gets or Sets AdUrl
        /// </summary>
        [DataMember(Name = "ad_url", IsRequired = true, EmitDefaultValue = true)]
        public string AdUrl { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [DataMember(Name = "image_url", IsRequired = true, EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets AdType
        /// </summary>
        [DataMember(Name = "ad_type", IsRequired = true, EmitDefaultValue = true)]
        public string AdType { get; set; }

        /// <summary>
        /// Gets or Sets PaidForBy
        /// </summary>
        [DataMember(Name = "paid_for_by", IsRequired = true, EmitDefaultValue = true)]
        public string PaidForBy { get; set; }

        /// <summary>
        /// Gets or Sets Advertiser
        /// </summary>
        [DataMember(Name = "advertiser", IsRequired = true, EmitDefaultValue = true)]
        public LinkedinAdAdvertiser Advertiser { get; set; }

        /// <summary>
        /// Gets or Sets Publisher
        /// </summary>
        [DataMember(Name = "publisher", IsRequired = true, EmitDefaultValue = true)]
        public LinkedinAdAdvertiser Publisher { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkedinAd {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  AdUrl: ").Append(AdUrl).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  AdType: ").Append(AdType).Append("\n");
            sb.Append("  PaidForBy: ").Append(PaidForBy).Append("\n");
            sb.Append("  Advertiser: ").Append(Advertiser).Append("\n");
            sb.Append("  Publisher: ").Append(Publisher).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) minLength
            if (this.Id != null && this.Id.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Id, length must be greater than 1.", new [] { "Id" });
            }

            yield break;
        }
    }

}
