/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// Heterogeneous post author — may be a person or a company. &#x60;username&#x60; is non-null only for people.
    /// </summary>
    [DataContract(Name = "LinkedinPostAuthor")]
    public partial class LinkedinPostAuthor : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinPostAuthor" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkedinPostAuthor() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinPostAuthor" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="urn">urn (required).</param>
        /// <param name="username">username (required).</param>
        /// <param name="displayName">displayName (required).</param>
        /// <param name="headline">headline (required).</param>
        /// <param name="url">url (required).</param>
        /// <param name="avatarUrl">avatarUrl (required).</param>
        /// <param name="accountType">accountType (required).</param>
        /// <param name="followerCount">followerCount (required).</param>
        public LinkedinPostAuthor(string id = default(string), string urn = default(string), string username = default(string), string displayName = default(string), string headline = default(string), string url = default(string), string avatarUrl = default(string), string accountType = default(string), int? followerCount = default(int?))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.Id = id;
            // to ensure "urn" is required (not null)
            if (urn == null)
            {
                throw new ArgumentNullException("urn is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.Urn = urn;
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.Username = username;
            // to ensure "displayName" is required (not null)
            if (displayName == null)
            {
                throw new ArgumentNullException("displayName is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.DisplayName = displayName;
            // to ensure "headline" is required (not null)
            if (headline == null)
            {
                throw new ArgumentNullException("headline is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.Headline = headline;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.Url = url;
            // to ensure "avatarUrl" is required (not null)
            if (avatarUrl == null)
            {
                throw new ArgumentNullException("avatarUrl is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.AvatarUrl = avatarUrl;
            // to ensure "accountType" is required (not null)
            if (accountType == null)
            {
                throw new ArgumentNullException("accountType is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.AccountType = accountType;
            // to ensure "followerCount" is required (not null)
            if (followerCount == null)
            {
                throw new ArgumentNullException("followerCount is a required property for LinkedinPostAuthor and cannot be null");
            }
            this.FollowerCount = followerCount;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Urn
        /// </summary>
        [DataMember(Name = "urn", IsRequired = true, EmitDefaultValue = true)]
        public string Urn { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "display_name", IsRequired = true, EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets Headline
        /// </summary>
        [DataMember(Name = "headline", IsRequired = true, EmitDefaultValue = true)]
        public string Headline { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets AvatarUrl
        /// </summary>
        [DataMember(Name = "avatar_url", IsRequired = true, EmitDefaultValue = true)]
        public string AvatarUrl { get; set; }

        /// <summary>
        /// Gets or Sets AccountType
        /// </summary>
        [DataMember(Name = "account_type", IsRequired = true, EmitDefaultValue = true)]
        public string AccountType { get; set; }

        /// <summary>
        /// Gets or Sets FollowerCount
        /// </summary>
        [DataMember(Name = "follower_count", IsRequired = true, EmitDefaultValue = true)]
        public int? FollowerCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkedinPostAuthor {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Urn: ").Append(Urn).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Headline: ").Append(Headline).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  AvatarUrl: ").Append(AvatarUrl).Append("\n");
            sb.Append("  AccountType: ").Append(AccountType).Append("\n");
            sb.Append("  FollowerCount: ").Append(FollowerCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
