/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// LinkedinComment
    /// </summary>
    [DataContract(Name = "LinkedinComment")]
    public partial class LinkedinComment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinComment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkedinComment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinComment" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="urn">urn (required).</param>
        /// <param name="text">text (required).</param>
        /// <param name="createTime">createTime (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="likeCount">likeCount (required).</param>
        /// <param name="replyCount">replyCount (required).</param>
        /// <param name="isPinned">isPinned (required).</param>
        /// <param name="isEdited">isEdited (required).</param>
        /// <param name="isAuthor">isAuthor (required).</param>
        /// <param name="hasPreviousReplies">hasPreviousReplies (required).</param>
        /// <param name="previousRepliesToken">previousRepliesToken (required).</param>
        /// <param name="reactions">reactions (required).</param>
        /// <param name="commenter">commenter (required).</param>
        public LinkedinComment(string id = default(string), string urn = default(string), string text = default(string), int createTime = default(int), string createdAt = default(string), int likeCount = default(int), int replyCount = default(int), bool isPinned = default(bool), bool isEdited = default(bool), bool isAuthor = default(bool), bool hasPreviousReplies = default(bool), string previousRepliesToken = default(string), List<LinkedinPostReactionsInner> reactions = default(List<LinkedinPostReactionsInner>), LinkedinCommentCommenter commenter = default(LinkedinCommentCommenter))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for LinkedinComment and cannot be null");
            }
            this.Id = id;
            // to ensure "urn" is required (not null)
            if (urn == null)
            {
                throw new ArgumentNullException("urn is a required property for LinkedinComment and cannot be null");
            }
            this.Urn = urn;
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for LinkedinComment and cannot be null");
            }
            this.Text = text;
            this.CreateTime = createTime;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for LinkedinComment and cannot be null");
            }
            this.CreatedAt = createdAt;
            this.LikeCount = likeCount;
            this.ReplyCount = replyCount;
            this.IsPinned = isPinned;
            this.IsEdited = isEdited;
            this.IsAuthor = isAuthor;
            this.HasPreviousReplies = hasPreviousReplies;
            // to ensure "previousRepliesToken" is required (not null)
            if (previousRepliesToken == null)
            {
                throw new ArgumentNullException("previousRepliesToken is a required property for LinkedinComment and cannot be null");
            }
            this.PreviousRepliesToken = previousRepliesToken;
            // to ensure "reactions" is required (not null)
            if (reactions == null)
            {
                throw new ArgumentNullException("reactions is a required property for LinkedinComment and cannot be null");
            }
            this.Reactions = reactions;
            // to ensure "commenter" is required (not null)
            if (commenter == null)
            {
                throw new ArgumentNullException("commenter is a required property for LinkedinComment and cannot be null");
            }
            this.Commenter = commenter;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Urn
        /// </summary>
        [DataMember(Name = "urn", IsRequired = true, EmitDefaultValue = true)]
        public string Urn { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets CreateTime
        /// </summary>
        [DataMember(Name = "create_time", IsRequired = true, EmitDefaultValue = true)]
        public int CreateTime { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets LikeCount
        /// </summary>
        [DataMember(Name = "like_count", IsRequired = true, EmitDefaultValue = true)]
        public int LikeCount { get; set; }

        /// <summary>
        /// Gets or Sets ReplyCount
        /// </summary>
        [DataMember(Name = "reply_count", IsRequired = true, EmitDefaultValue = true)]
        public int ReplyCount { get; set; }

        /// <summary>
        /// Gets or Sets IsPinned
        /// </summary>
        [DataMember(Name = "is_pinned", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPinned { get; set; }

        /// <summary>
        /// Gets or Sets IsEdited
        /// </summary>
        [DataMember(Name = "is_edited", IsRequired = true, EmitDefaultValue = true)]
        public bool IsEdited { get; set; }

        /// <summary>
        /// Gets or Sets IsAuthor
        /// </summary>
        [DataMember(Name = "is_author", IsRequired = true, EmitDefaultValue = true)]
        public bool IsAuthor { get; set; }

        /// <summary>
        /// Gets or Sets HasPreviousReplies
        /// </summary>
        [DataMember(Name = "has_previous_replies", IsRequired = true, EmitDefaultValue = true)]
        public bool HasPreviousReplies { get; set; }

        /// <summary>
        /// Gets or Sets PreviousRepliesToken
        /// </summary>
        [DataMember(Name = "previous_replies_token", IsRequired = true, EmitDefaultValue = true)]
        public string PreviousRepliesToken { get; set; }

        /// <summary>
        /// Gets or Sets Reactions
        /// </summary>
        [DataMember(Name = "reactions", IsRequired = true, EmitDefaultValue = true)]
        public List<LinkedinPostReactionsInner> Reactions { get; set; }

        /// <summary>
        /// Gets or Sets Commenter
        /// </summary>
        [DataMember(Name = "commenter", IsRequired = true, EmitDefaultValue = true)]
        public LinkedinCommentCommenter Commenter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkedinComment {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Urn: ").Append(Urn).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  LikeCount: ").Append(LikeCount).Append("\n");
            sb.Append("  ReplyCount: ").Append(ReplyCount).Append("\n");
            sb.Append("  IsPinned: ").Append(IsPinned).Append("\n");
            sb.Append("  IsEdited: ").Append(IsEdited).Append("\n");
            sb.Append("  IsAuthor: ").Append(IsAuthor).Append("\n");
            sb.Append("  HasPreviousReplies: ").Append(HasPreviousReplies).Append("\n");
            sb.Append("  PreviousRepliesToken: ").Append(PreviousRepliesToken).Append("\n");
            sb.Append("  Reactions: ").Append(Reactions).Append("\n");
            sb.Append("  Commenter: ").Append(Commenter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) minLength
            if (this.Id != null && this.Id.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Id, length must be greater than 1.", new [] { "Id" });
            }

            yield break;
        }
    }

}
