/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// LinkedinUserReaction
    /// </summary>
    [DataContract(Name = "LinkedinUserReaction")]
    public partial class LinkedinUserReaction : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinUserReaction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkedinUserReaction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinUserReaction" /> class.
        /// </summary>
        /// <param name="reactionType">reactionType (required).</param>
        /// <param name="post">post (required).</param>
        public LinkedinUserReaction(string reactionType = default(string), LinkedinUserCommentPost post = default(LinkedinUserCommentPost))
        {
            // to ensure "reactionType" is required (not null)
            if (reactionType == null)
            {
                throw new ArgumentNullException("reactionType is a required property for LinkedinUserReaction and cannot be null");
            }
            this.ReactionType = reactionType;
            // to ensure "post" is required (not null)
            if (post == null)
            {
                throw new ArgumentNullException("post is a required property for LinkedinUserReaction and cannot be null");
            }
            this.Post = post;
        }

        /// <summary>
        /// Gets or Sets ReactionType
        /// </summary>
        [DataMember(Name = "reaction_type", IsRequired = true, EmitDefaultValue = true)]
        public string ReactionType { get; set; }

        /// <summary>
        /// Gets or Sets Post
        /// </summary>
        [DataMember(Name = "post", IsRequired = true, EmitDefaultValue = true)]
        public LinkedinUserCommentPost Post { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkedinUserReaction {\n");
            sb.Append("  ReactionType: ").Append(ReactionType).Append("\n");
            sb.Append("  Post: ").Append(Post).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
