/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// LinkedinJobSalary
    /// </summary>
    [DataContract(Name = "LinkedinJobSalary")]
    public partial class LinkedinJobSalary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinJobSalary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkedinJobSalary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinJobSalary" /> class.
        /// </summary>
        /// <param name="min">min (required).</param>
        /// <param name="max">max (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="payPeriod">payPeriod (required).</param>
        /// <param name="isPresent">isPresent (required).</param>
        public LinkedinJobSalary(string min = default(string), string max = default(string), string currency = default(string), string payPeriod = default(string), bool isPresent = default(bool))
        {
            // to ensure "min" is required (not null)
            if (min == null)
            {
                throw new ArgumentNullException("min is a required property for LinkedinJobSalary and cannot be null");
            }
            this.Min = min;
            // to ensure "max" is required (not null)
            if (max == null)
            {
                throw new ArgumentNullException("max is a required property for LinkedinJobSalary and cannot be null");
            }
            this.Max = max;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for LinkedinJobSalary and cannot be null");
            }
            this.Currency = currency;
            // to ensure "payPeriod" is required (not null)
            if (payPeriod == null)
            {
                throw new ArgumentNullException("payPeriod is a required property for LinkedinJobSalary and cannot be null");
            }
            this.PayPeriod = payPeriod;
            this.IsPresent = isPresent;
        }

        /// <summary>
        /// Gets or Sets Min
        /// </summary>
        [DataMember(Name = "min", IsRequired = true, EmitDefaultValue = true)]
        public string Min { get; set; }

        /// <summary>
        /// Gets or Sets Max
        /// </summary>
        [DataMember(Name = "max", IsRequired = true, EmitDefaultValue = true)]
        public string Max { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets PayPeriod
        /// </summary>
        [DataMember(Name = "pay_period", IsRequired = true, EmitDefaultValue = true)]
        public string PayPeriod { get; set; }

        /// <summary>
        /// Gets or Sets IsPresent
        /// </summary>
        [DataMember(Name = "is_present", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPresent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkedinJobSalary {\n");
            sb.Append("  Min: ").Append(Min).Append("\n");
            sb.Append("  Max: ").Append(Max).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  PayPeriod: ").Append(PayPeriod).Append("\n");
            sb.Append("  IsPresent: ").Append(IsPresent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
