/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// Aggregated employee insight returned by /companies/{id}/member-insights. Each insight is one row of a stat table (e.g. \&quot;Locations\&quot; → [{name: &#39;Redmond, WA&#39;, count: 12345}]).
    /// </summary>
    [DataContract(Name = "LinkedinMemberInsight")]
    public partial class LinkedinMemberInsight : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinMemberInsight" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkedinMemberInsight() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinMemberInsight" /> class.
        /// </summary>
        /// <param name="title">title (required).</param>
        /// <param name="insights">insights (required).</param>
        public LinkedinMemberInsight(string title = default(string), List<LinkedinMemberInsightInsightsInner> insights = default(List<LinkedinMemberInsightInsightsInner>))
        {
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for LinkedinMemberInsight and cannot be null");
            }
            this.Title = title;
            // to ensure "insights" is required (not null)
            if (insights == null)
            {
                throw new ArgumentNullException("insights is a required property for LinkedinMemberInsight and cannot be null");
            }
            this.Insights = insights;
        }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Insights
        /// </summary>
        [DataMember(Name = "insights", IsRequired = true, EmitDefaultValue = true)]
        public List<LinkedinMemberInsightInsightsInner> Insights { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkedinMemberInsight {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Insights: ").Append(Insights).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
