/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// LinkedinAffiliatedPage
    /// </summary>
    [DataContract(Name = "LinkedinAffiliatedPage")]
    public partial class LinkedinAffiliatedPage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinAffiliatedPage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkedinAffiliatedPage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedinAffiliatedPage" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="universalName">universalName (required).</param>
        /// <param name="linkedinUrl">linkedinUrl (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="speciality">speciality (required).</param>
        /// <param name="followerCount">followerCount (required).</param>
        /// <param name="logoUrl">logoUrl (required).</param>
        public LinkedinAffiliatedPage(string id = default(string), string name = default(string), string universalName = default(string), string linkedinUrl = default(string), string type = default(string), string speciality = default(string), int followerCount = default(int), string logoUrl = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for LinkedinAffiliatedPage and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for LinkedinAffiliatedPage and cannot be null");
            }
            this.Name = name;
            // to ensure "universalName" is required (not null)
            if (universalName == null)
            {
                throw new ArgumentNullException("universalName is a required property for LinkedinAffiliatedPage and cannot be null");
            }
            this.UniversalName = universalName;
            // to ensure "linkedinUrl" is required (not null)
            if (linkedinUrl == null)
            {
                throw new ArgumentNullException("linkedinUrl is a required property for LinkedinAffiliatedPage and cannot be null");
            }
            this.LinkedinUrl = linkedinUrl;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for LinkedinAffiliatedPage and cannot be null");
            }
            this.Type = type;
            // to ensure "speciality" is required (not null)
            if (speciality == null)
            {
                throw new ArgumentNullException("speciality is a required property for LinkedinAffiliatedPage and cannot be null");
            }
            this.Speciality = speciality;
            this.FollowerCount = followerCount;
            // to ensure "logoUrl" is required (not null)
            if (logoUrl == null)
            {
                throw new ArgumentNullException("logoUrl is a required property for LinkedinAffiliatedPage and cannot be null");
            }
            this.LogoUrl = logoUrl;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets UniversalName
        /// </summary>
        [DataMember(Name = "universal_name", IsRequired = true, EmitDefaultValue = true)]
        public string UniversalName { get; set; }

        /// <summary>
        /// Gets or Sets LinkedinUrl
        /// </summary>
        [DataMember(Name = "linkedin_url", IsRequired = true, EmitDefaultValue = true)]
        public string LinkedinUrl { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Speciality
        /// </summary>
        [DataMember(Name = "speciality", IsRequired = true, EmitDefaultValue = true)]
        public string Speciality { get; set; }

        /// <summary>
        /// Gets or Sets FollowerCount
        /// </summary>
        [DataMember(Name = "follower_count", IsRequired = true, EmitDefaultValue = true)]
        public int FollowerCount { get; set; }

        /// <summary>
        /// Gets or Sets LogoUrl
        /// </summary>
        [DataMember(Name = "logo_url", IsRequired = true, EmitDefaultValue = true)]
        public string LogoUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkedinAffiliatedPage {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UniversalName: ").Append(UniversalName).Append("\n");
            sb.Append("  LinkedinUrl: ").Append(LinkedinUrl).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Speciality: ").Append(Speciality).Append("\n");
            sb.Append("  FollowerCount: ").Append(FollowerCount).Append("\n");
            sb.Append("  LogoUrl: ").Append(LogoUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
