/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoAutocompleteSuggestion
    /// </summary>
    [DataContract(Name = "SeoAutocompleteSuggestion")]
    public partial class SeoAutocompleteSuggestion : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoAutocompleteSuggestion" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoAutocompleteSuggestion() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoAutocompleteSuggestion" /> class.
        /// </summary>
        /// <param name="rank">Absolute rank of the suggestion in the list..</param>
        /// <param name="suggestion">Google autocomplete keyword suggestion. (required).</param>
        /// <param name="relevance">Relevance score Google assigns to the suggestion..</param>
        /// <param name="suggestionType">Category Google assigns to the suggestion, such as Search or Navigation..</param>
        /// <param name="searchQueryUrl">Google search URL the suggestion resolves to..</param>
        /// <param name="thumbnailUrl">Thumbnail image URL when Google attaches one to the suggestion..</param>
        /// <param name="highlighted">Substrings highlighted by Google within the suggestion..</param>
        /// <param name="isBillable">Each suggestion is one billable record. (required).</param>
        public SeoAutocompleteSuggestion(int rank = default(int), string suggestion = default(string), int relevance = default(int), string suggestionType = default(string), string searchQueryUrl = default(string), string thumbnailUrl = default(string), List<string> highlighted = default(List<string>), bool isBillable = default(bool))
        {
            // to ensure "suggestion" is required (not null)
            if (suggestion == null)
            {
                throw new ArgumentNullException("suggestion is a required property for SeoAutocompleteSuggestion and cannot be null");
            }
            this.Suggestion = suggestion;
            this.IsBillable = isBillable;
            this.Rank = rank;
            this.Relevance = relevance;
            this.SuggestionType = suggestionType;
            this.SearchQueryUrl = searchQueryUrl;
            this.ThumbnailUrl = thumbnailUrl;
            this.Highlighted = highlighted;
        }

        /// <summary>
        /// Absolute rank of the suggestion in the list.
        /// </summary>
        /// <value>Absolute rank of the suggestion in the list.</value>
        [DataMember(Name = "rank", EmitDefaultValue = false)]
        public int Rank { get; set; }

        /// <summary>
        /// Google autocomplete keyword suggestion.
        /// </summary>
        /// <value>Google autocomplete keyword suggestion.</value>
        [DataMember(Name = "suggestion", IsRequired = true, EmitDefaultValue = true)]
        public string Suggestion { get; set; }

        /// <summary>
        /// Relevance score Google assigns to the suggestion.
        /// </summary>
        /// <value>Relevance score Google assigns to the suggestion.</value>
        [DataMember(Name = "relevance", EmitDefaultValue = false)]
        public int Relevance { get; set; }

        /// <summary>
        /// Category Google assigns to the suggestion, such as Search or Navigation.
        /// </summary>
        /// <value>Category Google assigns to the suggestion, such as Search or Navigation.</value>
        [DataMember(Name = "suggestion_type", EmitDefaultValue = false)]
        public string SuggestionType { get; set; }

        /// <summary>
        /// Google search URL the suggestion resolves to.
        /// </summary>
        /// <value>Google search URL the suggestion resolves to.</value>
        [DataMember(Name = "search_query_url", EmitDefaultValue = false)]
        public string SearchQueryUrl { get; set; }

        /// <summary>
        /// Thumbnail image URL when Google attaches one to the suggestion.
        /// </summary>
        /// <value>Thumbnail image URL when Google attaches one to the suggestion.</value>
        [DataMember(Name = "thumbnail_url", EmitDefaultValue = false)]
        public string ThumbnailUrl { get; set; }

        /// <summary>
        /// Substrings highlighted by Google within the suggestion.
        /// </summary>
        /// <value>Substrings highlighted by Google within the suggestion.</value>
        [DataMember(Name = "highlighted", EmitDefaultValue = false)]
        public List<string> Highlighted { get; set; }

        /// <summary>
        /// Each suggestion is one billable record.
        /// </summary>
        /// <value>Each suggestion is one billable record.</value>
        [DataMember(Name = "is_billable", IsRequired = true, EmitDefaultValue = true)]
        public bool IsBillable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoAutocompleteSuggestion {\n");
            sb.Append("  Rank: ").Append(Rank).Append("\n");
            sb.Append("  Suggestion: ").Append(Suggestion).Append("\n");
            sb.Append("  Relevance: ").Append(Relevance).Append("\n");
            sb.Append("  SuggestionType: ").Append(SuggestionType).Append("\n");
            sb.Append("  SearchQueryUrl: ").Append(SearchQueryUrl).Append("\n");
            sb.Append("  ThumbnailUrl: ").Append(ThumbnailUrl).Append("\n");
            sb.Append("  Highlighted: ").Append(Highlighted).Append("\n");
            sb.Append("  IsBillable: ").Append(IsBillable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
