/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoBacklinksBulkNewLostReferringDomainsResponse
    /// </summary>
    [DataContract(Name = "SeoBacklinksBulkNewLostReferringDomainsResponse")]
    public partial class SeoBacklinksBulkNewLostReferringDomainsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksBulkNewLostReferringDomainsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoBacklinksBulkNewLostReferringDomainsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksBulkNewLostReferringDomainsResponse" /> class.
        /// </summary>
        /// <param name="results">New and lost referring domain counts for each requested target. Each target is one billable record. (required).</param>
        public SeoBacklinksBulkNewLostReferringDomainsResponse(List<SeoBacklinksBulkNewLostReferringDomainsItem> results = default(List<SeoBacklinksBulkNewLostReferringDomainsItem>))
        {
            // to ensure "results" is required (not null)
            if (results == null)
            {
                throw new ArgumentNullException("results is a required property for SeoBacklinksBulkNewLostReferringDomainsResponse and cannot be null");
            }
            this.Results = results;
        }

        /// <summary>
        /// New and lost referring domain counts for each requested target. Each target is one billable record.
        /// </summary>
        /// <value>New and lost referring domain counts for each requested target. Each target is one billable record.</value>
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<SeoBacklinksBulkNewLostReferringDomainsItem> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoBacklinksBulkNewLostReferringDomainsResponse {\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
