/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoBulkTrafficRequest
    /// </summary>
    [DataContract(Name = "SeoBulkTrafficRequest")]
    public partial class SeoBulkTrafficRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets View
        /// </summary>
        [DataMember(Name = "view", EmitDefaultValue = false)]
        public SeoDomainMetricsView? View { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBulkTrafficRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoBulkTrafficRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBulkTrafficRequest" /> class.
        /// </summary>
        /// <param name="targets">Domains to estimate traffic for (1-1000). (required).</param>
        /// <param name="location">location.</param>
        /// <param name="language">Search language as an ISO code or full language name. Defaults to en..</param>
        /// <param name="view">view.</param>
        public SeoBulkTrafficRequest(List<string> targets = default(List<string>), SeoBulkTrafficLocation location = default(SeoBulkTrafficLocation), string language = default(string), SeoDomainMetricsView? view = default(SeoDomainMetricsView?))
        {
            // to ensure "targets" is required (not null)
            if (targets == null)
            {
                throw new ArgumentNullException("targets is a required property for SeoBulkTrafficRequest and cannot be null");
            }
            this.Targets = targets;
            this.Location = location;
            this.Language = language;
            this.View = view;
        }

        /// <summary>
        /// Domains to estimate traffic for (1-1000).
        /// </summary>
        /// <value>Domains to estimate traffic for (1-1000).</value>
        [DataMember(Name = "targets", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Targets { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", EmitDefaultValue = false)]
        public SeoBulkTrafficLocation Location { get; set; }

        /// <summary>
        /// Search language as an ISO code or full language name. Defaults to en.
        /// </summary>
        /// <value>Search language as an ISO code or full language name. Defaults to en.</value>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoBulkTrafficRequest {\n");
            sb.Append("  Targets: ").Append(Targets).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  View: ").Append(View).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Language (string) maxLength
            if (this.Language != null && this.Language.Length > 80)
            {
                yield return new ValidationResult("Invalid value for Language, length must be less than 80.", new [] { "Language" });
            }

            // Language (string) minLength
            if (this.Language != null && this.Language.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Language, length must be greater than 2.", new [] { "Language" });
            }

            yield break;
        }
    }

}
