/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoBacklinksPageIntersectionItem
    /// </summary>
    [DataContract(Name = "SeoBacklinksPageIntersectionItem")]
    public partial class SeoBacklinksPageIntersectionItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksPageIntersectionItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoBacklinksPageIntersectionItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksPageIntersectionItem" /> class.
        /// </summary>
        /// <param name="urlFrom">URL of the referring page that links to the targets..</param>
        /// <param name="domainFrom">Domain of the referring page..</param>
        /// <param name="intersectionsCount">Number of the requested targets this page links to..</param>
        /// <param name="linksTo">Backlinks from this referring page to each requested target it links to, one entry per target. (required).</param>
        public SeoBacklinksPageIntersectionItem(string urlFrom = default(string), string domainFrom = default(string), int intersectionsCount = default(int), List<SeoBacklinksPageIntersectionTargetLinks> linksTo = default(List<SeoBacklinksPageIntersectionTargetLinks>))
        {
            // to ensure "linksTo" is required (not null)
            if (linksTo == null)
            {
                throw new ArgumentNullException("linksTo is a required property for SeoBacklinksPageIntersectionItem and cannot be null");
            }
            this.LinksTo = linksTo;
            this.UrlFrom = urlFrom;
            this.DomainFrom = domainFrom;
            this.IntersectionsCount = intersectionsCount;
        }

        /// <summary>
        /// URL of the referring page that links to the targets.
        /// </summary>
        /// <value>URL of the referring page that links to the targets.</value>
        [DataMember(Name = "url_from", EmitDefaultValue = false)]
        public string UrlFrom { get; set; }

        /// <summary>
        /// Domain of the referring page.
        /// </summary>
        /// <value>Domain of the referring page.</value>
        [DataMember(Name = "domain_from", EmitDefaultValue = false)]
        public string DomainFrom { get; set; }

        /// <summary>
        /// Number of the requested targets this page links to.
        /// </summary>
        /// <value>Number of the requested targets this page links to.</value>
        [DataMember(Name = "intersections_count", EmitDefaultValue = false)]
        public int IntersectionsCount { get; set; }

        /// <summary>
        /// Backlinks from this referring page to each requested target it links to, one entry per target.
        /// </summary>
        /// <value>Backlinks from this referring page to each requested target it links to, one entry per target.</value>
        [DataMember(Name = "links_to", IsRequired = true, EmitDefaultValue = true)]
        public List<SeoBacklinksPageIntersectionTargetLinks> LinksTo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoBacklinksPageIntersectionItem {\n");
            sb.Append("  UrlFrom: ").Append(UrlFrom).Append("\n");
            sb.Append("  DomainFrom: ").Append(DomainFrom).Append("\n");
            sb.Append("  IntersectionsCount: ").Append(IntersectionsCount).Append("\n");
            sb.Append("  LinksTo: ").Append(LinksTo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
