/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoBacklinksDomainIntersectionTargetMetrics
    /// </summary>
    [DataContract(Name = "SeoBacklinksDomainIntersectionTargetMetrics")]
    public partial class SeoBacklinksDomainIntersectionTargetMetrics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksDomainIntersectionTargetMetrics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoBacklinksDomainIntersectionTargetMetrics() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksDomainIntersectionTargetMetrics" /> class.
        /// </summary>
        /// <param name="target">The requested target these metrics describe. (required).</param>
        /// <param name="metrics">metrics (required).</param>
        public SeoBacklinksDomainIntersectionTargetMetrics(string target = default(string), SeoBacklinksDomainIntersectionTargetMetricsMetrics metrics = default(SeoBacklinksDomainIntersectionTargetMetricsMetrics))
        {
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for SeoBacklinksDomainIntersectionTargetMetrics and cannot be null");
            }
            this.Target = target;
            // to ensure "metrics" is required (not null)
            if (metrics == null)
            {
                throw new ArgumentNullException("metrics is a required property for SeoBacklinksDomainIntersectionTargetMetrics and cannot be null");
            }
            this.Metrics = metrics;
        }

        /// <summary>
        /// The requested target these metrics describe.
        /// </summary>
        /// <value>The requested target these metrics describe.</value>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; }

        /// <summary>
        /// Gets or Sets Metrics
        /// </summary>
        [DataMember(Name = "metrics", IsRequired = true, EmitDefaultValue = true)]
        public SeoBacklinksDomainIntersectionTargetMetricsMetrics Metrics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoBacklinksDomainIntersectionTargetMetrics {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Metrics: ").Append(Metrics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
