/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoBacklinksCompetitorItem
    /// </summary>
    [DataContract(Name = "SeoBacklinksCompetitorItem")]
    public partial class SeoBacklinksCompetitorItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksCompetitorItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoBacklinksCompetitorItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksCompetitorItem" /> class.
        /// </summary>
        /// <param name="target">Competing domain that shares part of the target&#39;s backlink profile. (required).</param>
        /// <param name="rank">Backlink rank of the competing domain (0-1000 by default)..</param>
        /// <param name="intersections">Number of referring domains the competitor shares with the target..</param>
        public SeoBacklinksCompetitorItem(string target = default(string), int rank = default(int), int intersections = default(int))
        {
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for SeoBacklinksCompetitorItem and cannot be null");
            }
            this.Target = target;
            this.Rank = rank;
            this.Intersections = intersections;
        }

        /// <summary>
        /// Competing domain that shares part of the target&#39;s backlink profile.
        /// </summary>
        /// <value>Competing domain that shares part of the target&#39;s backlink profile.</value>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; }

        /// <summary>
        /// Backlink rank of the competing domain (0-1000 by default).
        /// </summary>
        /// <value>Backlink rank of the competing domain (0-1000 by default).</value>
        [DataMember(Name = "rank", EmitDefaultValue = false)]
        public int Rank { get; set; }

        /// <summary>
        /// Number of referring domains the competitor shares with the target.
        /// </summary>
        /// <value>Number of referring domains the competitor shares with the target.</value>
        [DataMember(Name = "intersections", EmitDefaultValue = false)]
        public int Intersections { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoBacklinksCompetitorItem {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Rank: ").Append(Rank).Append("\n");
            sb.Append("  Intersections: ").Append(Intersections).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
