/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoBacklinksHistoryRequest
    /// </summary>
    [DataContract(Name = "SeoBacklinksHistoryRequest")]
    public partial class SeoBacklinksHistoryRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets RankScale
        /// </summary>
        [DataMember(Name = "rank_scale", EmitDefaultValue = false)]
        public SeoBacklinksRankScale? RankScale { get; set; }

        /// <summary>
        /// Gets or Sets View
        /// </summary>
        [DataMember(Name = "view", EmitDefaultValue = false)]
        public SeoBacklinksView? View { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksHistoryRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoBacklinksHistoryRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoBacklinksHistoryRequest" /> class.
        /// </summary>
        /// <param name="target">Domain, subdomain, or page to analyze. A domain or subdomain is specified without https:// and www. (example.com); a page is specified as an absolute URL (https://example.com/blog/). (required).</param>
        /// <param name="dateFrom">Start date (yyyy-mm-dd) for the history. Minimum 2019-01-30; defaults to one year ago..</param>
        /// <param name="dateTo">End date (yyyy-mm-dd). Defaults to today..</param>
        /// <param name="rankScale">rankScale.</param>
        /// <param name="view">view.</param>
        public SeoBacklinksHistoryRequest(string target = default(string), string dateFrom = default(string), string dateTo = default(string), SeoBacklinksRankScale? rankScale = default(SeoBacklinksRankScale?), SeoBacklinksView? view = default(SeoBacklinksView?))
        {
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for SeoBacklinksHistoryRequest and cannot be null");
            }
            this.Target = target;
            this.DateFrom = dateFrom;
            this.DateTo = dateTo;
            this.RankScale = rankScale;
            this.View = view;
        }

        /// <summary>
        /// Domain, subdomain, or page to analyze. A domain or subdomain is specified without https:// and www. (example.com); a page is specified as an absolute URL (https://example.com/blog/).
        /// </summary>
        /// <value>Domain, subdomain, or page to analyze. A domain or subdomain is specified without https:// and www. (example.com); a page is specified as an absolute URL (https://example.com/blog/).</value>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; }

        /// <summary>
        /// Start date (yyyy-mm-dd) for the history. Minimum 2019-01-30; defaults to one year ago.
        /// </summary>
        /// <value>Start date (yyyy-mm-dd) for the history. Minimum 2019-01-30; defaults to one year ago.</value>
        [DataMember(Name = "date_from", EmitDefaultValue = false)]
        public string DateFrom { get; set; }

        /// <summary>
        /// End date (yyyy-mm-dd). Defaults to today.
        /// </summary>
        /// <value>End date (yyyy-mm-dd). Defaults to today.</value>
        [DataMember(Name = "date_to", EmitDefaultValue = false)]
        public string DateTo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoBacklinksHistoryRequest {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  DateFrom: ").Append(DateFrom).Append("\n");
            sb.Append("  DateTo: ").Append(DateTo).Append("\n");
            sb.Append("  RankScale: ").Append(RankScale).Append("\n");
            sb.Append("  View: ").Append(View).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Target (string) maxLength
            if (this.Target != null && this.Target.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for Target, length must be less than 2048.", new [] { "Target" });
            }

            // Target (string) minLength
            if (this.Target != null && this.Target.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Target, length must be greater than 1.", new [] { "Target" });
            }

            yield break;
        }
    }

}
