/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoCompetitorsDomainResponse
    /// </summary>
    [DataContract(Name = "SeoCompetitorsDomainResponse")]
    public partial class SeoCompetitorsDomainResponse : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets View
        /// </summary>
        [DataMember(Name = "view", IsRequired = true, EmitDefaultValue = true)]
        public SeoDomainMetricsView View { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoCompetitorsDomainResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoCompetitorsDomainResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoCompetitorsDomainResponse" /> class.
        /// </summary>
        /// <param name="target">Target domain echoed from the request. (required).</param>
        /// <param name="location">location (required).</param>
        /// <param name="language">language (required).</param>
        /// <param name="view">view (required).</param>
        /// <param name="totalCount">Total number of competing domains available in DataForSEO&#39;s database..</param>
        /// <param name="results">Domains competing with the target, with shared-keyword counts and traffic metrics. Each domain is one billable record. (required).</param>
        public SeoCompetitorsDomainResponse(string target = default(string), string location = default(string), string language = default(string), SeoDomainMetricsView view = default(SeoDomainMetricsView), int totalCount = default(int), List<SeoCompetitorDomainItem> results = default(List<SeoCompetitorDomainItem>))
        {
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for SeoCompetitorsDomainResponse and cannot be null");
            }
            this.Target = target;
            // to ensure "location" is required (not null)
            if (location == null)
            {
                throw new ArgumentNullException("location is a required property for SeoCompetitorsDomainResponse and cannot be null");
            }
            this.Location = location;
            // to ensure "language" is required (not null)
            if (language == null)
            {
                throw new ArgumentNullException("language is a required property for SeoCompetitorsDomainResponse and cannot be null");
            }
            this.Language = language;
            this.View = view;
            // to ensure "results" is required (not null)
            if (results == null)
            {
                throw new ArgumentNullException("results is a required property for SeoCompetitorsDomainResponse and cannot be null");
            }
            this.Results = results;
            this.TotalCount = totalCount;
        }

        /// <summary>
        /// Target domain echoed from the request.
        /// </summary>
        /// <value>Target domain echoed from the request.</value>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", IsRequired = true, EmitDefaultValue = true)]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name = "language", IsRequired = true, EmitDefaultValue = true)]
        public string Language { get; set; }

        /// <summary>
        /// Total number of competing domains available in DataForSEO&#39;s database.
        /// </summary>
        /// <value>Total number of competing domains available in DataForSEO&#39;s database.</value>
        [DataMember(Name = "total_count", EmitDefaultValue = false)]
        public int TotalCount { get; set; }

        /// <summary>
        /// Domains competing with the target, with shared-keyword counts and traffic metrics. Each domain is one billable record.
        /// </summary>
        /// <value>Domains competing with the target, with shared-keyword counts and traffic metrics. Each domain is one billable record.</value>
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<SeoCompetitorDomainItem> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoCompetitorsDomainResponse {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  View: ").Append(View).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
