/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoDomainRankOverviewRequest
    /// </summary>
    [DataContract(Name = "SeoDomainRankOverviewRequest")]
    public partial class SeoDomainRankOverviewRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets View
        /// </summary>
        [DataMember(Name = "view", EmitDefaultValue = false)]
        public SeoDomainMetricsView? View { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoDomainRankOverviewRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoDomainRankOverviewRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoDomainRankOverviewRequest" /> class.
        /// </summary>
        /// <param name="target">Target domain, such as example.com or https://example.com. Specified without www. (required).</param>
        /// <param name="location">location.</param>
        /// <param name="language">Search language as an ISO code or full language name. Defaults to en..</param>
        /// <param name="view">view.</param>
        public SeoDomainRankOverviewRequest(string target = default(string), SeoDomainRankOverviewLocation location = default(SeoDomainRankOverviewLocation), string language = default(string), SeoDomainMetricsView? view = default(SeoDomainMetricsView?))
        {
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for SeoDomainRankOverviewRequest and cannot be null");
            }
            this.Target = target;
            this.Location = location;
            this.Language = language;
            this.View = view;
        }

        /// <summary>
        /// Target domain, such as example.com or https://example.com. Specified without www.
        /// </summary>
        /// <value>Target domain, such as example.com or https://example.com. Specified without www.</value>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", EmitDefaultValue = false)]
        public SeoDomainRankOverviewLocation Location { get; set; }

        /// <summary>
        /// Search language as an ISO code or full language name. Defaults to en.
        /// </summary>
        /// <value>Search language as an ISO code or full language name. Defaults to en.</value>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoDomainRankOverviewRequest {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  View: ").Append(View).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Target (string) maxLength
            if (this.Target != null && this.Target.Length > 253)
            {
                yield return new ValidationResult("Invalid value for Target, length must be less than 253.", new [] { "Target" });
            }

            // Target (string) minLength
            if (this.Target != null && this.Target.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Target, length must be greater than 1.", new [] { "Target" });
            }

            // Language (string) maxLength
            if (this.Language != null && this.Language.Length > 80)
            {
                yield return new ValidationResult("Invalid value for Language, length must be less than 80.", new [] { "Language" });
            }

            // Language (string) minLength
            if (this.Language != null && this.Language.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Language, length must be greater than 2.", new [] { "Language" });
            }

            yield break;
        }
    }

}
