/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoHistoricalRankItem
    /// </summary>
    [DataContract(Name = "SeoHistoricalRankItem")]
    public partial class SeoHistoricalRankItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoHistoricalRankItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoHistoricalRankItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoHistoricalRankItem" /> class.
        /// </summary>
        /// <param name="year">Year of the metrics snapshot. (required).</param>
        /// <param name="month">Month of the metrics snapshot (1-12)..</param>
        /// <param name="organic">organic.</param>
        /// <param name="paid">paid.</param>
        public SeoHistoricalRankItem(int year = default(int), int month = default(int), SeoDomainMetricGroup organic = default(SeoDomainMetricGroup), SeoDomainMetricsPaid paid = default(SeoDomainMetricsPaid))
        {
            this.Year = year;
            this.Month = month;
            this.Organic = organic;
            this.Paid = paid;
        }

        /// <summary>
        /// Year of the metrics snapshot.
        /// </summary>
        /// <value>Year of the metrics snapshot.</value>
        [DataMember(Name = "year", IsRequired = true, EmitDefaultValue = true)]
        public int Year { get; set; }

        /// <summary>
        /// Month of the metrics snapshot (1-12).
        /// </summary>
        /// <value>Month of the metrics snapshot (1-12).</value>
        [DataMember(Name = "month", EmitDefaultValue = false)]
        public int Month { get; set; }

        /// <summary>
        /// Gets or Sets Organic
        /// </summary>
        [DataMember(Name = "organic", EmitDefaultValue = false)]
        public SeoDomainMetricGroup Organic { get; set; }

        /// <summary>
        /// Gets or Sets Paid
        /// </summary>
        [DataMember(Name = "paid", EmitDefaultValue = false)]
        public SeoDomainMetricsPaid Paid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoHistoricalRankItem {\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  Month: ").Append(Month).Append("\n");
            sb.Append("  Organic: ").Append(Organic).Append("\n");
            sb.Append("  Paid: ").Append(Paid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
