/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoSerpQuestion
    /// </summary>
    [DataContract(Name = "SeoSerpQuestion")]
    public partial class SeoSerpQuestion : IValidatableObject
    {
        /// <summary>
        /// Defines Source
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SourceEnum
        {
            /// <summary>
            /// Enum PeopleAlsoAsk for value: people_also_ask
            /// </summary>
            [EnumMember(Value = "people_also_ask")]
            PeopleAlsoAsk = 1
        }


        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name = "source", IsRequired = true, EmitDefaultValue = true)]
        public SourceEnum Source { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSerpQuestion" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoSerpQuestion() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSerpQuestion" /> class.
        /// </summary>
        /// <param name="question">question (required).</param>
        /// <param name="rank">rank.</param>
        /// <param name="source">source (required).</param>
        public SeoSerpQuestion(string question = default(string), int rank = default(int), SourceEnum source = default(SourceEnum))
        {
            // to ensure "question" is required (not null)
            if (question == null)
            {
                throw new ArgumentNullException("question is a required property for SeoSerpQuestion and cannot be null");
            }
            this.Question = question;
            this.Source = source;
            this.Rank = rank;
        }

        /// <summary>
        /// Gets or Sets Question
        /// </summary>
        [DataMember(Name = "question", IsRequired = true, EmitDefaultValue = true)]
        public string Question { get; set; }

        /// <summary>
        /// Gets or Sets Rank
        /// </summary>
        [DataMember(Name = "rank", EmitDefaultValue = false)]
        public int Rank { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoSerpQuestion {\n");
            sb.Append("  Question: ").Append(Question).Append("\n");
            sb.Append("  Rank: ").Append(Rank).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
