/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoSubdomainItem
    /// </summary>
    [DataContract(Name = "SeoSubdomainItem")]
    public partial class SeoSubdomainItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSubdomainItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoSubdomainItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSubdomainItem" /> class.
        /// </summary>
        /// <param name="subdomain">Subdomain of the target domain. (required).</param>
        /// <param name="metrics">metrics.</param>
        public SeoSubdomainItem(string subdomain = default(string), SeoSubdomainItemMetrics metrics = default(SeoSubdomainItemMetrics))
        {
            // to ensure "subdomain" is required (not null)
            if (subdomain == null)
            {
                throw new ArgumentNullException("subdomain is a required property for SeoSubdomainItem and cannot be null");
            }
            this.Subdomain = subdomain;
            this.Metrics = metrics;
        }

        /// <summary>
        /// Subdomain of the target domain.
        /// </summary>
        /// <value>Subdomain of the target domain.</value>
        [DataMember(Name = "subdomain", IsRequired = true, EmitDefaultValue = true)]
        public string Subdomain { get; set; }

        /// <summary>
        /// Gets or Sets Metrics
        /// </summary>
        [DataMember(Name = "metrics", EmitDefaultValue = false)]
        public SeoSubdomainItemMetrics Metrics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoSubdomainItem {\n");
            sb.Append("  Subdomain: ").Append(Subdomain).Append("\n");
            sb.Append("  Metrics: ").Append(Metrics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
