/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoSerpCompetitor
    /// </summary>
    [DataContract(Name = "SeoSerpCompetitor")]
    public partial class SeoSerpCompetitor : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSerpCompetitor" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoSerpCompetitor() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSerpCompetitor" /> class.
        /// </summary>
        /// <param name="domain">domain (required).</param>
        /// <param name="bestRank">bestRank.</param>
        /// <param name="resultCount">resultCount (required).</param>
        public SeoSerpCompetitor(string domain = default(string), int bestRank = default(int), int resultCount = default(int))
        {
            // to ensure "domain" is required (not null)
            if (domain == null)
            {
                throw new ArgumentNullException("domain is a required property for SeoSerpCompetitor and cannot be null");
            }
            this.Domain = domain;
            this.ResultCount = resultCount;
            this.BestRank = bestRank;
        }

        /// <summary>
        /// Gets or Sets Domain
        /// </summary>
        [DataMember(Name = "domain", IsRequired = true, EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or Sets BestRank
        /// </summary>
        [DataMember(Name = "best_rank", EmitDefaultValue = false)]
        public int BestRank { get; set; }

        /// <summary>
        /// Gets or Sets ResultCount
        /// </summary>
        [DataMember(Name = "result_count", IsRequired = true, EmitDefaultValue = true)]
        public int ResultCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoSerpCompetitor {\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  BestRank: ").Append(BestRank).Append("\n");
            sb.Append("  ResultCount: ").Append(ResultCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
