/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// SeoSerpTarget
    /// </summary>
    [DataContract(Name = "SeoSerpTarget")]
    public partial class SeoSerpTarget : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSerpTarget" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeoSerpTarget() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSerpTarget" /> class.
        /// </summary>
        /// <param name="value">value (required).</param>
        /// <param name="domain">domain.</param>
        /// <param name="present">present (required).</param>
        /// <param name="bestRank">bestRank.</param>
        /// <param name="matches">matches (required).</param>
        public SeoSerpTarget(string value = default(string), string domain = default(string), bool present = default(bool), int bestRank = default(int), List<SeoSerpResultRef> matches = default(List<SeoSerpResultRef>))
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for SeoSerpTarget and cannot be null");
            }
            this.Value = value;
            this.Present = present;
            // to ensure "matches" is required (not null)
            if (matches == null)
            {
                throw new ArgumentNullException("matches is a required property for SeoSerpTarget and cannot be null");
            }
            this.Matches = matches;
            this.Domain = domain;
            this.BestRank = bestRank;
        }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets Domain
        /// </summary>
        [DataMember(Name = "domain", EmitDefaultValue = false)]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or Sets Present
        /// </summary>
        [DataMember(Name = "present", IsRequired = true, EmitDefaultValue = true)]
        public bool Present { get; set; }

        /// <summary>
        /// Gets or Sets BestRank
        /// </summary>
        [DataMember(Name = "best_rank", EmitDefaultValue = false)]
        public int BestRank { get; set; }

        /// <summary>
        /// Gets or Sets Matches
        /// </summary>
        [DataMember(Name = "matches", IsRequired = true, EmitDefaultValue = true)]
        public List<SeoSerpResultRef> Matches { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoSerpTarget {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  Present: ").Append(Present).Append("\n");
            sb.Append("  BestRank: ").Append(BestRank).Append("\n");
            sb.Append("  Matches: ").Append(Matches).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
