/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// Where the first domain ranks for the keyword.
    /// </summary>
    [DataContract(Name = "SeoSerpElement")]
    public partial class SeoSerpElement : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeoSerpElement" /> class.
        /// </summary>
        /// <param name="rankGroup">Position in SERP grouping organic results together (ignores ads/features)..</param>
        /// <param name="rankAbsolute">Absolute position in SERP counting every element..</param>
        /// <param name="position">Side of the SERP the element appears on: left or right..</param>
        /// <param name="domain">Domain that holds the ranking page..</param>
        /// <param name="title">Title of the ranking page..</param>
        /// <param name="url">URL of the ranking page..</param>
        /// <param name="etv">Estimated monthly traffic the keyword sends to this URL..</param>
        /// <param name="estimatedPaidTrafficCost">Estimated monthly ad cost (USD) of the traffic this URL receives..</param>
        public SeoSerpElement(int rankGroup = default(int), int rankAbsolute = default(int), string position = default(string), string domain = default(string), string title = default(string), string url = default(string), decimal etv = default(decimal), decimal estimatedPaidTrafficCost = default(decimal))
        {
            this.RankGroup = rankGroup;
            this.RankAbsolute = rankAbsolute;
            this.Position = position;
            this.Domain = domain;
            this.Title = title;
            this.Url = url;
            this.Etv = etv;
            this.EstimatedPaidTrafficCost = estimatedPaidTrafficCost;
        }

        /// <summary>
        /// Position in SERP grouping organic results together (ignores ads/features).
        /// </summary>
        /// <value>Position in SERP grouping organic results together (ignores ads/features).</value>
        [DataMember(Name = "rank_group", EmitDefaultValue = false)]
        public int RankGroup { get; set; }

        /// <summary>
        /// Absolute position in SERP counting every element.
        /// </summary>
        /// <value>Absolute position in SERP counting every element.</value>
        [DataMember(Name = "rank_absolute", EmitDefaultValue = false)]
        public int RankAbsolute { get; set; }

        /// <summary>
        /// Side of the SERP the element appears on: left or right.
        /// </summary>
        /// <value>Side of the SERP the element appears on: left or right.</value>
        [DataMember(Name = "position", EmitDefaultValue = false)]
        public string Position { get; set; }

        /// <summary>
        /// Domain that holds the ranking page.
        /// </summary>
        /// <value>Domain that holds the ranking page.</value>
        [DataMember(Name = "domain", EmitDefaultValue = false)]
        public string Domain { get; set; }

        /// <summary>
        /// Title of the ranking page.
        /// </summary>
        /// <value>Title of the ranking page.</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// URL of the ranking page.
        /// </summary>
        /// <value>URL of the ranking page.</value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Estimated monthly traffic the keyword sends to this URL.
        /// </summary>
        /// <value>Estimated monthly traffic the keyword sends to this URL.</value>
        [DataMember(Name = "etv", EmitDefaultValue = false)]
        public decimal Etv { get; set; }

        /// <summary>
        /// Estimated monthly ad cost (USD) of the traffic this URL receives.
        /// </summary>
        /// <value>Estimated monthly ad cost (USD) of the traffic this URL receives.</value>
        [DataMember(Name = "estimated_paid_traffic_cost", EmitDefaultValue = false)]
        public decimal EstimatedPaidTrafficCost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeoSerpElement {\n");
            sb.Append("  RankGroup: ").Append(RankGroup).Append("\n");
            sb.Append("  RankAbsolute: ").Append(RankAbsolute).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Etv: ").Append(Etv).Append("\n");
            sb.Append("  EstimatedPaidTrafficCost: ").Append(EstimatedPaidTrafficCost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
