/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// ThreadsUser
    /// </summary>
    [DataContract(Name = "ThreadsUser")]
    public partial class ThreadsUser : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreadsUser" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ThreadsUser() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreadsUser" /> class.
        /// </summary>
        /// <param name="id">Threads URL slug (&#x60;username&#x60;). (required).</param>
        /// <param name="userId">Numeric Threads pk; surfaced for callers that want to skip the gateway-side username → pk stitch. (required).</param>
        /// <param name="username">username (required).</param>
        /// <param name="fullName">fullName (required).</param>
        /// <param name="biography">biography (required).</param>
        /// <param name="profilePicUrl">profilePicUrl (required).</param>
        /// <param name="followerCount">followerCount (required).</param>
        /// <param name="isVerified">isVerified (required).</param>
        /// <param name="isPrivate">isPrivate (required).</param>
        public ThreadsUser(string id = default(string), string userId = default(string), string username = default(string), string fullName = default(string), string biography = default(string), string profilePicUrl = default(string), decimal followerCount = default(decimal), bool isVerified = default(bool), bool isPrivate = default(bool))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ThreadsUser and cannot be null");
            }
            this.Id = id;
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for ThreadsUser and cannot be null");
            }
            this.UserId = userId;
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for ThreadsUser and cannot be null");
            }
            this.Username = username;
            // to ensure "fullName" is required (not null)
            if (fullName == null)
            {
                throw new ArgumentNullException("fullName is a required property for ThreadsUser and cannot be null");
            }
            this.FullName = fullName;
            // to ensure "biography" is required (not null)
            if (biography == null)
            {
                throw new ArgumentNullException("biography is a required property for ThreadsUser and cannot be null");
            }
            this.Biography = biography;
            // to ensure "profilePicUrl" is required (not null)
            if (profilePicUrl == null)
            {
                throw new ArgumentNullException("profilePicUrl is a required property for ThreadsUser and cannot be null");
            }
            this.ProfilePicUrl = profilePicUrl;
            this.FollowerCount = followerCount;
            this.IsVerified = isVerified;
            this.IsPrivate = isPrivate;
        }

        /// <summary>
        /// Threads URL slug (&#x60;username&#x60;).
        /// </summary>
        /// <value>Threads URL slug (&#x60;username&#x60;).</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Numeric Threads pk; surfaced for callers that want to skip the gateway-side username → pk stitch.
        /// </summary>
        /// <value>Numeric Threads pk; surfaced for callers that want to skip the gateway-side username → pk stitch.</value>
        [DataMember(Name = "user_id", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets FullName
        /// </summary>
        [DataMember(Name = "full_name", IsRequired = true, EmitDefaultValue = true)]
        public string FullName { get; set; }

        /// <summary>
        /// Gets or Sets Biography
        /// </summary>
        [DataMember(Name = "biography", IsRequired = true, EmitDefaultValue = true)]
        public string Biography { get; set; }

        /// <summary>
        /// Gets or Sets ProfilePicUrl
        /// </summary>
        [DataMember(Name = "profile_pic_url", IsRequired = true, EmitDefaultValue = true)]
        public string ProfilePicUrl { get; set; }

        /// <summary>
        /// Gets or Sets FollowerCount
        /// </summary>
        [DataMember(Name = "follower_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal FollowerCount { get; set; }

        /// <summary>
        /// Gets or Sets IsVerified
        /// </summary>
        [DataMember(Name = "is_verified", IsRequired = true, EmitDefaultValue = true)]
        public bool IsVerified { get; set; }

        /// <summary>
        /// Gets or Sets IsPrivate
        /// </summary>
        [DataMember(Name = "is_private", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPrivate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ThreadsUser {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  FullName: ").Append(FullName).Append("\n");
            sb.Append("  Biography: ").Append(Biography).Append("\n");
            sb.Append("  ProfilePicUrl: ").Append(ProfilePicUrl).Append("\n");
            sb.Append("  FollowerCount: ").Append(FollowerCount).Append("\n");
            sb.Append("  IsVerified: ").Append(IsVerified).Append("\n");
            sb.Append("  IsPrivate: ").Append(IsPrivate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) minLength
            if (this.Id != null && this.Id.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Id, length must be greater than 1.", new [] { "Id" });
            }

            yield break;
        }
    }

}
