/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// XMedia
    /// </summary>
    [DataContract(Name = "XMedia")]
    public partial class XMedia : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XMedia" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected XMedia() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="XMedia" /> class.
        /// </summary>
        /// <param name="mediaKey">mediaKey.</param>
        /// <param name="type">type (required).</param>
        /// <param name="url">url.</param>
        /// <param name="previewImageUrl">previewImageUrl.</param>
        /// <param name="height">height.</param>
        /// <param name="width">width.</param>
        /// <param name="durationMs">durationMs.</param>
        /// <param name="variants">variants.</param>
        public XMedia(string mediaKey = default(string), string type = default(string), string url = default(string), string previewImageUrl = default(string), decimal height = default(decimal), decimal width = default(decimal), decimal durationMs = default(decimal), List<XMediaVariantsInner> variants = default(List<XMediaVariantsInner>))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for XMedia and cannot be null");
            }
            this.Type = type;
            this.MediaKey = mediaKey;
            this.Url = url;
            this.PreviewImageUrl = previewImageUrl;
            this.Height = height;
            this.Width = width;
            this.DurationMs = durationMs;
            this.Variants = variants;
        }

        /// <summary>
        /// Gets or Sets MediaKey
        /// </summary>
        [DataMember(Name = "media_key", EmitDefaultValue = false)]
        public string MediaKey { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets PreviewImageUrl
        /// </summary>
        [DataMember(Name = "preview_image_url", EmitDefaultValue = false)]
        public string PreviewImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", EmitDefaultValue = false)]
        public decimal Height { get; set; }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", EmitDefaultValue = false)]
        public decimal Width { get; set; }

        /// <summary>
        /// Gets or Sets DurationMs
        /// </summary>
        [DataMember(Name = "duration_ms", EmitDefaultValue = false)]
        public decimal DurationMs { get; set; }

        /// <summary>
        /// Gets or Sets Variants
        /// </summary>
        [DataMember(Name = "variants", EmitDefaultValue = false)]
        public List<XMediaVariantsInner> Variants { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class XMedia {\n");
            sb.Append("  MediaKey: ").Append(MediaKey).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  PreviewImageUrl: ").Append(PreviewImageUrl).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  DurationMs: ").Append(DurationMs).Append("\n");
            sb.Append("  Variants: ").Append(Variants).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
