/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// XTrend
    /// </summary>
    [DataContract(Name = "XTrend")]
    public partial class XTrend : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XTrend" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected XTrend() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="XTrend" /> class.
        /// </summary>
        /// <param name="trendName">trendName (required).</param>
        /// <param name="tweetCount">tweetCount.</param>
        /// <param name="rank">rank.</param>
        /// <param name="query">query.</param>
        public XTrend(string trendName = default(string), decimal tweetCount = default(decimal), decimal rank = default(decimal), string query = default(string))
        {
            // to ensure "trendName" is required (not null)
            if (trendName == null)
            {
                throw new ArgumentNullException("trendName is a required property for XTrend and cannot be null");
            }
            this.TrendName = trendName;
            this.TweetCount = tweetCount;
            this.Rank = rank;
            this.Query = query;
        }

        /// <summary>
        /// Gets or Sets TrendName
        /// </summary>
        [DataMember(Name = "trend_name", IsRequired = true, EmitDefaultValue = true)]
        public string TrendName { get; set; }

        /// <summary>
        /// Gets or Sets TweetCount
        /// </summary>
        [DataMember(Name = "tweet_count", EmitDefaultValue = false)]
        public decimal TweetCount { get; set; }

        /// <summary>
        /// Gets or Sets Rank
        /// </summary>
        [DataMember(Name = "rank", EmitDefaultValue = false)]
        public decimal Rank { get; set; }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [DataMember(Name = "query", EmitDefaultValue = false)]
        public string Query { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class XTrend {\n");
            sb.Append("  TrendName: ").Append(TrendName).Append("\n");
            sb.Append("  TweetCount: ").Append(TweetCount).Append("\n");
            sb.Append("  Rank: ").Append(Rank).Append("\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
