/*
 * UnifAPI
 *
 * Unified, AI-friendly API for public-data providers. Single source of truth for the UnifAPI gateway — consumed by docs (Fumadocs), the marketing site, and downstream SDK generators.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@unifapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Unifapi.Sdk.Client.OpenAPIDateConverter;

namespace Unifapi.Sdk.Model
{
    /// <summary>
    /// YouTubeChannel
    /// </summary>
    [DataContract(Name = "YouTubeChannel")]
    public partial class YouTubeChannel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="YouTubeChannel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected YouTubeChannel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="YouTubeChannel" /> class.
        /// </summary>
        /// <param name="id">YouTube channel id (&#x60;UCxxx&#x60;). (required).</param>
        /// <param name="title">title (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="avatarUrl">avatarUrl (required).</param>
        /// <param name="bannerUrl">bannerUrl (required).</param>
        /// <param name="subscriberCount">subscriberCount (required).</param>
        /// <param name="videoCount">videoCount (required).</param>
        /// <param name="viewCount">viewCount (required).</param>
        /// <param name="country">country (required).</param>
        /// <param name="isVerified">isVerified (required).</param>
        /// <param name="createdAt">Source creation date string (passed through). (required).</param>
        public YouTubeChannel(string id = default(string), string title = default(string), string description = default(string), string avatarUrl = default(string), string bannerUrl = default(string), decimal subscriberCount = default(decimal), decimal videoCount = default(decimal), decimal viewCount = default(decimal), string country = default(string), bool isVerified = default(bool), string createdAt = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for YouTubeChannel and cannot be null");
            }
            this.Id = id;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for YouTubeChannel and cannot be null");
            }
            this.Title = title;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for YouTubeChannel and cannot be null");
            }
            this.Description = description;
            // to ensure "avatarUrl" is required (not null)
            if (avatarUrl == null)
            {
                throw new ArgumentNullException("avatarUrl is a required property for YouTubeChannel and cannot be null");
            }
            this.AvatarUrl = avatarUrl;
            // to ensure "bannerUrl" is required (not null)
            if (bannerUrl == null)
            {
                throw new ArgumentNullException("bannerUrl is a required property for YouTubeChannel and cannot be null");
            }
            this.BannerUrl = bannerUrl;
            this.SubscriberCount = subscriberCount;
            this.VideoCount = videoCount;
            this.ViewCount = viewCount;
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for YouTubeChannel and cannot be null");
            }
            this.Country = country;
            this.IsVerified = isVerified;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for YouTubeChannel and cannot be null");
            }
            this.CreatedAt = createdAt;
        }

        /// <summary>
        /// YouTube channel id (&#x60;UCxxx&#x60;).
        /// </summary>
        /// <value>YouTube channel id (&#x60;UCxxx&#x60;).</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets AvatarUrl
        /// </summary>
        [DataMember(Name = "avatar_url", IsRequired = true, EmitDefaultValue = true)]
        public string AvatarUrl { get; set; }

        /// <summary>
        /// Gets or Sets BannerUrl
        /// </summary>
        [DataMember(Name = "banner_url", IsRequired = true, EmitDefaultValue = true)]
        public string BannerUrl { get; set; }

        /// <summary>
        /// Gets or Sets SubscriberCount
        /// </summary>
        [DataMember(Name = "subscriber_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal SubscriberCount { get; set; }

        /// <summary>
        /// Gets or Sets VideoCount
        /// </summary>
        [DataMember(Name = "video_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal VideoCount { get; set; }

        /// <summary>
        /// Gets or Sets ViewCount
        /// </summary>
        [DataMember(Name = "view_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal ViewCount { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets IsVerified
        /// </summary>
        [DataMember(Name = "is_verified", IsRequired = true, EmitDefaultValue = true)]
        public bool IsVerified { get; set; }

        /// <summary>
        /// Source creation date string (passed through).
        /// </summary>
        /// <value>Source creation date string (passed through).</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class YouTubeChannel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  AvatarUrl: ").Append(AvatarUrl).Append("\n");
            sb.Append("  BannerUrl: ").Append(BannerUrl).Append("\n");
            sb.Append("  SubscriberCount: ").Append(SubscriberCount).Append("\n");
            sb.Append("  VideoCount: ").Append(VideoCount).Append("\n");
            sb.Append("  ViewCount: ").Append(ViewCount).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  IsVerified: ").Append(IsVerified).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) minLength
            if (this.Id != null && this.Id.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Id, length must be greater than 1.", new [] { "Id" });
            }

            yield break;
        }
    }

}
